REPORT ZYNY_MP_ROW_COLOR_CHANGE_11.

TYPE-POOLS: SLIS.

DATA: CONTAINER   TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GRID1       TYPE REF TO CL_GUI_ALV_GRID,
      G_CONTAINER TYPE SCRFNAME VALUE 'CCONTAINER'.

DATA : TY_LAY1     TYPE LVC_S_LAYO,
       IT_FIELDCAT TYPE LVC_T_FCAT,
       TY_FIELDCAT TYPE LVC_S_FCAT.

TYPES : BEGIN OF T_MARA,
          MATNR   TYPE MATNR,
          ERSDA   TYPE ERSDA,
          ERNAM   TYPE ERNAM,
          MTART   TYPE MTART,
          CELLTAB TYPE LVC_T_STYL, " field used for editing the perticular cell
          LINE_COLOR TYPE LVC_T_SCOL, "FIELD TO CHNAGE CELL COLOR INDIVIDUALLY
        END OF T_MARA.

DATA :LT_MARA TYPE TABLE OF T_MARA,
      LS_MARA TYPE T_MARA.

PARAMETERS : P_COUNT TYPE I DEFAULT 10.

START-OF-SELECTION.
  SELECT MATNR
         ERSDA
         ERNAM
         MTART
    FROM MARA
    INTO CORRESPONDING FIELDS OF TABLE LT_MARA UP TO P_COUNT ROWS.

  CALL SCREEN 9021 .

*&---------------------------------------------------------------------*
*&      Module  STATUS_9021  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_9021 OUTPUT.
  SET PF-STATUS 'TEST'.
  IF CONTAINER IS INITIAL.

    CREATE OBJECT CONTAINER
      EXPORTING
        CONTAINER_NAME = G_CONTAINER.
    CREATE OBJECT GRID1
      EXPORTING
        I_PARENT = CONTAINER.

*************fieldcatalog creation creation
    TY_FIELDCAT-ROW_POS = 1.
    TY_FIELDCAT-COL_POS = 1.
    TY_FIELDCAT-FIELDNAME = 'MATNR'.
    TY_FIELDCAT-COLTEXT = 'MATNR'.
*    ty_fieldcat-edit = 'X'.  " code used to make only  column(matnr) editable
    TY_FIELDCAT-OUTPUTLEN = 20.
    APPEND TY_FIELDCAT TO IT_FIELDCAT.
    CLEAR TY_FIELDCAT.

    TY_FIELDCAT-ROW_POS = 1.
    TY_FIELDCAT-COL_POS = 2.
    TY_FIELDCAT-FIELDNAME = 'ERSDA'.
    TY_FIELDCAT-COLTEXT = 'ERSDA'.
    TY_FIELDCAT-OUTPUTLEN = 10.
    APPEND TY_FIELDCAT TO IT_FIELDCAT.
    CLEAR TY_FIELDCAT.

    TY_FIELDCAT-ROW_POS = 1.
    TY_FIELDCAT-COL_POS = 3.
    TY_FIELDCAT-FIELDNAME = 'ERNAM'.
    TY_FIELDCAT-COLTEXT = 'ERNAM'.
    TY_FIELDCAT-OUTPUTLEN = 20.            " Used to modify the output field length
    APPEND TY_FIELDCAT TO IT_FIELDCAT.
    CLEAR TY_FIELDCAT.

    TY_FIELDCAT-ROW_POS = 1.
    TY_FIELDCAT-COL_POS = 4.
    TY_FIELDCAT-FIELDNAME = 'MTART'.
    TY_FIELDCAT-COLTEXT = 'MTART'.
    TY_FIELDCAT-OUTPUTLEN = 10.
    APPEND TY_FIELDCAT TO IT_FIELDCAT.
    CLEAR TY_FIELDCAT.

***********layout of fieldcat
*    ty_lay1-no_toolbar = 'X'.
    TY_LAY1-SEL_MODE = 'A'. " THIS ALLOWS TO SELECT ROWS
    TY_LAY1-STYLEFNAME = 'CELLTAB'. "FIELD IN TABLE TO STORE THE STYLES
    TY_LAY1-CTAB_FNAME = 'LINE_COLOR'. "FIELD IN TABLE WHICH STORES THE ROW CELLS COLOR PROPERTIES

    CALL METHOD GRID1->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT       = TY_LAY1
*i_structure_name = 'MARA'
      CHANGING
        IT_OUTTAB       = LT_MARA[]
        IT_FIELDCATALOG = IT_FIELDCAT.
  ENDIF.
ENDMODULE.
*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_9021  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_9021 INPUT.
  CASE SY-UCOMM.
    WHEN 'EDIT'.
      PERFORM EDIT_MODE.
    WHEN 'CHANGE'.
      PERFORM CHANGE_ROW.
    WHEN 'BACK'.
      LEAVE TO SCREEN 0.
    WHEN 'CANCEL'.
      LEAVE PROGRAM.
    WHEN 'EXIT'.
      LEAVE TO SCREEN 0.
  ENDCASE.
ENDMODULE.

FORM EDIT_MODE .
  DATA : LT_ROW_NO     TYPE LVC_T_ROID,
         LS_ROW_NO     TYPE LVC_S_ROID,
         LS_STYLEROW   TYPE LVC_S_STYL,
         LT_STYLEROW   TYPE TABLE OF LVC_S_STYL.

  CALL METHOD GRID1->GET_SELECTED_ROWS
    IMPORTING
      ET_ROW_NO = LT_ROW_NO.

  IF NOT LT_ROW_NO IS INITIAL.

    LOOP AT LT_MARA INTO LS_MARA.
      READ TABLE LT_ROW_NO INTO LS_ROW_NO WITH KEY ROW_ID = SY-TABIX.
      IF SY-SUBRC = 0.
        LS_STYLEROW-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        LS_STYLEROW-FIELDNAME = 'MATNR'.
        INSERT LS_STYLEROW INTO TABLE LT_STYLEROW.

        LS_STYLEROW-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_ENABLED.
        LS_STYLEROW-FIELDNAME = 'ERSDA'.
        INSERT LS_STYLEROW INTO TABLE LT_STYLEROW.

        LS_STYLEROW-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        LS_STYLEROW-FIELDNAME = 'ERNAM'.
        INSERT LS_STYLEROW INTO TABLE LT_STYLEROW.

        LS_STYLEROW-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_ENABLED.
        LS_STYLEROW-FIELDNAME = 'MTART'.
        INSERT LS_STYLEROW INTO TABLE LT_STYLEROW.

        CLEAR: LS_MARA-CELLTAB.
        INSERT LINES OF LT_STYLEROW INTO TABLE LS_MARA-CELLTAB.
        MODIFY LT_MARA FROM LS_MARA TRANSPORTING CELLTAB.
        CLEAR: LT_STYLEROW.
      ELSE.
        LS_STYLEROW-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        LS_STYLEROW-FIELDNAME = 'MATNR'.
        INSERT LS_STYLEROW INTO TABLE LT_STYLEROW.

        LS_STYLEROW-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        LS_STYLEROW-FIELDNAME = 'ERSDA'.
        INSERT LS_STYLEROW INTO TABLE LT_STYLEROW.

        LS_STYLEROW-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        LS_STYLEROW-FIELDNAME = 'ERNAM'.
        INSERT LS_STYLEROW INTO TABLE LT_STYLEROW.

        LS_STYLEROW-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        LS_STYLEROW-FIELDNAME = 'MTART'.
        INSERT LS_STYLEROW INTO TABLE LT_STYLEROW.

        CLEAR: LS_MARA-CELLTAB.
        INSERT LINES OF LT_STYLEROW INTO TABLE LS_MARA-CELLTAB.
        MODIFY LT_MARA FROM LS_MARA TRANSPORTING CELLTAB.
        CLEAR: LT_STYLEROW.
      ENDIF.
    ENDLOOP.
  ENDIF.

  GRID1->CHECK_CHANGED_DATA( ).  " used to reflect the change value in alv display

  CLEAR LT_ROW_NO.
  CLEAR LS_ROW_NO.

  IF GRID1->IS_READY_FOR_INPUT( ) EQ 0.
    CALL METHOD GRID1->SET_READY_FOR_INPUT
      EXPORTING
        I_READY_FOR_INPUT = 1.

  ELSE.
    CALL METHOD GRID1->SET_READY_FOR_INPUT
      EXPORTING
        I_READY_FOR_INPUT = 0.
  ENDIF.
  GRID1->REFRESH_TABLE_DISPLAY( ).
ENDFORM.

FORM CHANGE_ROW.
  DATA : LT_ROW_NO     TYPE LVC_T_ROID,
         LS_ROW_NO     TYPE LVC_S_ROID.
  DATA : LT_CELL_COLORS TYPE LVC_T_SCOL .
  DATA : LS_CELL_COLORS TYPE LVC_S_SCOL .

" GETTING THE LIST OF SELECTED ROWS
  CALL METHOD GRID1->GET_SELECTED_ROWS
    IMPORTING
      ET_ROW_NO = LT_ROW_NO.

* CHECKING IF LIST IS NOT EMPTY
  IF NOT LT_ROW_NO IS INITIAL.

* LOOPING THROUGH DATA
    LOOP AT LT_MARA INTO LS_MARA.

      " HERER ROW_ID AND SY-TABIX, INETRSECTION MEANS THE ROW SELECTED
      READ TABLE LT_ROW_NO INTO LS_ROW_NO WITH KEY ROW_ID = SY-TABIX.

      IF SY-SUBRC = 0.
            TRANSLATE LS_MARA-MATNR TO LOWER CASE.
            LS_CELL_COLORS-FNAME = 'MATNR'.
            LS_CELL_COLORS-COLOR-COL = '1'.
            LS_CELL_COLORS-COLOR-INV = '1'.
            INSERT LS_CELL_COLORS INTO TABLE LT_CELL_COLORS.

            TRANSLATE LS_MARA-ERSDA TO LOWER CASE.
            LS_CELL_COLORS-FNAME = 'ERSDA'.
            LS_CELL_COLORS-COLOR-COL = '1'.
            LS_CELL_COLORS-COLOR-INV = '1'.
            INSERT LS_CELL_COLORS INTO TABLE LT_CELL_COLORS.

            TRANSLATE LS_MARA-ERNAM TO LOWER CASE.
            LS_CELL_COLORS-FNAME = 'ERNAM'.
            LS_CELL_COLORS-COLOR-COL = '1'.
            LS_CELL_COLORS-COLOR-INV = '1'.
            INSERT LS_CELL_COLORS INTO TABLE LT_CELL_COLORS.

            TRANSLATE LS_MARA-MTART TO LOWER CASE.
            LS_CELL_COLORS-FNAME = 'MTART'.
            LS_CELL_COLORS-COLOR-COL = '1'.
            LS_CELL_COLORS-COLOR-INV = '1'.
            INSERT LS_CELL_COLORS INTO TABLE LT_CELL_COLORS.

            CLEAR: LS_MARA-LINE_COLOR.
            INSERT LINES OF LT_CELL_COLORS INTO TABLE LS_MARA-LINE_COLOR.
            MODIFY LT_MARA FROM LS_MARA." TRANSPORTING LINE_COLOR.
        ENDIF.
    ENDLOOP.
  ENDIF.
  GRID1->CHECK_CHANGED_DATA( ).  " used to reflect the change value in alv display

  CLEAR LT_ROW_NO.
  CLEAR LS_ROW_NO.

  GRID1->REFRESH_TABLE_DISPLAY( ).
ENDFORM.