REPORT Z.
TABLES SPFLI.
TYPE-POOLS SLIS.

DATA IT_SPFLI TYPE TABLE OF SPFLI .
DATA IT_FCAT TYPE SLIS_T_FIELDCAT_ALV .
SELECT-OPTIONS S_CARRID FOR SPFLI-CARRID.

START-OF-SELECTION .
  PERFORM GET_DATA .
  PERFORM CREATE_FCAT.
  PERFORM DISP_ALV .

FORM GET_DATA .
  SELECT * FROM SPFLI
      INTO TABLE IT_SPFLI
      WHERE CARRID IN S_CARRID.
ENDFORM.                    " GET_DATA

FORM CREATE_FCAT.
  CALL FUNCTION 'REUSE_ALV_FIELDCATALOG_MERGE'
    EXPORTING
      I_STRUCTURE_NAME = 'SPFLI'
    CHANGING
      CT_FIELDCAT      = IT_FCAT[].
ENDFORM.
" CREATE_FCAT

FORM DISP_ALV .
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      IT_FIELDCAT = IT_FCAT "PASS FIELD CATALOG TO ALV
    TABLES
      T_OUTTAB    = IT_SPFLI.
ENDFORM.                    " DISP_ALV