REPORT  Z.
TYPE-POOLS SLIS .
TABLES SPFLI.
*DATA DECLARATIONS
TYPES : BEGIN OF TY_SPFLI,  "User defined internal table type
          CARRID    TYPE SPFLI-CARRID,
          CONNID    TYPE SPFLI-CONNID,
          COUNTRYFR TYPE SPFLI-COUNTRYFR,
          CITYFROM  TYPE SPFLI-CITYFROM,
        END OF TY_SPFLI.
DATA IT_SPFLI TYPE TABLE OF TY_SPFLI .
DATA WA_SPFLI TYPE TY_SPFLI .
*ALV DECLARATIONS
DATA IT_FCAT TYPE SLIS_T_FIELDCAT_ALV .
DATA WA_FCAT TYPE SLIS_FIELDCAT_ALV .
DATA V_POS TYPE I .

DATA WA_LAYOUT TYPE SLIS_LAYOUT_ALV .
SELECT-OPTIONS S_CARRID FOR SPFLI-CARRID.

START-OF-SELECTION .
  PERFORM GET_DATA .
  PERFORM CREATE_FCAT .
  PERFORM CREATE_LAYOUT.
  PERFORM DISPLAY_DATA .

FORM GET_DATA .
   SELECT CARRID CONNID COUNTRYFR CITYFROM FROM SPFLI
      INTO TABLE IT_SPFLI
      WHERE CARRID IN S_CARRID.
ENDFORM.                    " GET_DATA

FORM DISPLAY_DATA .
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      IS_LAYOUT          = WA_LAYOUT
      IT_FIELDCAT        = IT_FCAT
    TABLES
      T_OUTTAB           = IT_SPFLI.
ENDFORM.                    " DISPLAY_DATA

FORM CREATE_FCAT .
  V_POS = 1 .
  WA_FCAT-COL_POS = V_POS.
  WA_FCAT-FIELDNAME = 'CARRID' .
  WA_FCAT-SELTEXT_M = 'Airline' .
  WA_FCAT-HOTSPOT = 'X' .
  APPEND WA_FCAT TO IT_FCAT .
  CLEAR WA_FCAT .

  V_POS = V_POS + 1.
  WA_FCAT-COL_POS = V_POS .
  WA_FCAT-FIELDNAME = 'CONNID' .
  WA_FCAT-SELTEXT_M = 'Flight Number' .
  APPEND WA_FCAT TO IT_FCAT .
  CLEAR WA_FCAT .

  V_POS = V_POS +  1.
  WA_FCAT-COL_POS = V_POS .
  WA_FCAT-FIELDNAME = 'COUNTRYFR' .
  WA_FCAT-SELTEXT_M = 'Country From' .
  APPEND WA_FCAT TO IT_FCAT .
  CLEAR WA_FCAT .

  V_POS = V_POS +  1.
  WA_FCAT-COL_POS = V_POS .
  WA_FCAT-FIELDNAME = 'CITYFROM' .
  WA_FCAT-SELTEXT_M = 'Departure City' .
  APPEND WA_FCAT TO IT_FCAT .
  CLEAR WA_FCAT .
ENDFORM.                    " CREATE_FCAT

FORM CREATE_LAYOUT .
  WA_LAYOUT-ZEBRA = 'X' .
  WA_LAYOUT-COLWIDTH_OPTIMIZE = 'X' .
  WA_LAYOUT-NO_VLINE = 'X' .
  WA_LAYOUT-NO_HLINE = 'X' .
ENDFORM.                    " CREATE_LAYOUT