REPORT Z.
TABLES SPFLI. "DECLARE TABLE FOR SELECT-OPTIONS
DATA IT_SPFLI TYPE TABLE OF SPFLI. "DECLARE INTERNAL TABLE FOR SPFLI
SELECT-OPTIONS: S_CARRID FOR SPFLI-CARRID. "PRINT SELECT-OPTIONS FOR MATNR
START-OF-SELECTION.
SELECT * FROM SPFLI INTO TABLE IT_SPFLI
                   WHERE CARRID IN S_CARRID .
CALL FUNCTION 'REUSE_ALV_LIST_DISPLAY' "CALL FUNCTION MODULE TO DISPLAY ALV GRID
EXPORTING
I_STRUCTURE_NAME = 'SPFLI'
TABLES
T_OUTTAB = IT_SPFLI. "PASS INTERNAL TABLE TO DISPLAY ALV FORMAT