REPORT Z.

TYPES : BEGIN OF TY_SPFLI,  "User defined internal table type
          CARRID    TYPE SPFLI-CARRID,
          CONNID    TYPE SPFLI-CONNID,
          COUNTRYFR TYPE SPFLI-COUNTRYFR,
          CITYFROM  TYPE SPFLI-CITYFROM,
        END OF TY_SPFLI.

DATA : IT_SPFLI TYPE TABLE OF TY_SPFLI, "SPFLI internal table
       WA_SPFLI TYPE TY_SPFLI. "work area

TYPES : BEGIN OF TY_SFLIGHT,
          CARRID TYPE SFLIGHT-CARRID,
          CONNID TYPE SFLIGHT-CONNID,
          FLDATE TYPE SFLIGHT-FLDATE,
          PRICE  TYPE SFLIGHT-PRICE,
        END OF TY_SFLIGHT.

DATA : IT_SFLIGHT TYPE TABLE OF TY_SFLIGHT, "SFLIGHT internal table
       WA_SFLIGHT TYPE TY_SFLIGHT.

DATA T_FCAT TYPE SLIS_T_FIELDCAT_ALV. "field catalog
DATA W_FCAT LIKE LINE OF T_FCAT.

DATA IT_KEY TYPE SLIS_KEYINFO_ALV.

PARAMETERS P_CARRID TYPE SPFLI-CARRID. "CARRID type input

START-OF-SELECTION.
  PERFORM GET_DATA.
  PERFORM CREATE_FCAT.
  PERFORM HIERARCHYDISPLAY.

FORM GET_DATA.
  SELECT CARRID
         CONNID
         COUNTRYFR
         CITYFROM
         FROM SPFLI "get SPFLI data
    INTO TABLE IT_SPFLI  WHERE CARRID = P_CARRID.

  IF NOT IT_SPFLI IS INITIAL .
    SELECT  CARRID CONNID
            FLDATE
            PRICE FROM SFLIGHT INTO TABLE IT_SFLIGHT "get flight data
      FOR ALL ENTRIES IN IT_SPFLI WHERE CARRID = IT_SPFLI-CARRID.
  ENDIF.
ENDFORM.

FORM CREATE_FCAT.
  W_FCAT-COL_POS       = '1'. "coloum position
  W_FCAT-FIELDNAME     = 'CARRID'. "column name
  W_FCAT-TABNAME       = 'IT_SPFLI'. "table
  W_FCAT-REF_TABNAME   = 'SPFLI'. "table
  W_FCAT-REF_FIELDNAME = 'CARRID'. "reference field, it will show descriptions automatically
  APPEND W_FCAT TO T_FCAT.
  CLEAR W_FCAT.

  W_FCAT-COL_POS       = '2'.
  W_FCAT-FIELDNAME     = 'CONNID'.
  W_FCAT-TABNAME       = 'IT_SPFLI'.
  W_FCAT-REF_TABNAME   = 'SPFLI'.
  W_FCAT-REF_FIELDNAME = 'CONNID'.
  APPEND W_FCAT TO T_FCAT.
  CLEAR W_FCAT.

  W_FCAT-COL_POS       = '3'.
  W_FCAT-FIELDNAME     = 'COUNTRYFR'.
  W_FCAT-TABNAME       = 'IT_SPFLI'.
  W_FCAT-REF_TABNAME   = 'SPFLI'.
  W_FCAT-REF_FIELDNAME = 'COUNTRYFR'.
  APPEND W_FCAT TO T_FCAT.
  CLEAR W_FCAT.

  W_FCAT-COL_POS       = '4'.
  W_FCAT-FIELDNAME     = 'CITYFROM'.
  W_FCAT-TABNAME       = 'IT_SPFLI'.
  W_FCAT-REF_TABNAME   = 'SPFLI'.
  W_FCAT-REF_FIELDNAME = 'CITYFROM'.
  APPEND W_FCAT TO T_FCAT.
  CLEAR W_FCAT.

***build fcat for SFLIGHT
  W_FCAT-COL_POS       = '1'.
  W_FCAT-FIELDNAME     = 'CARRID'.
  W_FCAT-TABNAME       = 'IT_SFLIGHT'.
  W_FCAT-REF_TABNAME   = 'SFLIGHT'.
  W_FCAT-FIELDNAME = 'CARRID'.
  APPEND W_FCAT TO T_FCAT.
  CLEAR W_FCAT.

  W_FCAT-COL_POS       = '2'.
  W_FCAT-FIELDNAME     = 'CONNID'.
  W_FCAT-TABNAME       = 'IT_SFLIGHT'.
  W_FCAT-REF_TABNAME   = 'SFLIGHT'.
  W_FCAT-REF_FIELDNAME = 'CONNID'.
  APPEND W_FCAT TO T_FCAT.
  CLEAR W_FCAT.

  W_FCAT-COL_POS       = '2'.
  W_FCAT-FIELDNAME     = 'FLDATE'.
  W_FCAT-TABNAME       = 'IT_SFLIGHT'.
  W_FCAT-REF_TABNAME   = 'SFLIGHT'.
  W_FCAT-REF_FIELDNAME = 'FLDATE'.
  APPEND W_FCAT TO T_FCAT.
  CLEAR W_FCAT.

  W_FCAT-COL_POS       = '3'.
  W_FCAT-FIELDNAME     = 'PRICE'.
  W_FCAT-TABNAME       = 'IT_SFLIGHT'.
  W_FCAT-REF_TABNAME   = 'SFLIGHT'.
  W_FCAT-REF_FIELDNAME = 'PRICE'.
  APPEND W_FCAT TO T_FCAT.
  CLEAR W_FCAT.

ENDFORM.

FORM HIERARCHYDISPLAY.
  IT_KEY-HEADER01 =  'CARRID'. "SPFLI
  IT_KEY-ITEM01 =    'CARRID'. "SFLIGHT
  IT_KEY-HEADER01 =  'CONNID'. "SPFLI
  IT_KEY-ITEM01 =    'CONNID'. "SFLIGHT

  CALL FUNCTION 'REUSE_ALV_HIERSEQ_LIST_DISPLAY'
    EXPORTING
      IT_FIELDCAT      = T_FCAT[]
      I_TABNAME_HEADER = 'IT_SPFLI'
      I_TABNAME_ITEM   = 'IT_SFLIGHT'
      IS_KEYINFO       = IT_KEY
    TABLES
      T_OUTTAB_HEADER  = IT_SPFLI
      T_OUTTAB_ITEM    = IT_SFLIGHT.
ENDFORM.