REPORT Z.

DATA IT_TAB TYPE TABLE OF ZSTAFF_MASTER.

 PARAMETERS P_FILE TYPE RLGRAP-FILENAME.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.

  CALL FUNCTION 'F4_FILENAME'
   EXPORTING
     PROGRAM_NAME        = SYST-CPROG
     DYNPRO_NUMBER       = SYST-DYNNR
   IMPORTING
    FILE_NAME           = P_FILE
            .

START-OF-SELECTION.

DATA P_FILE1 TYPE STRING.

P_FILE1 = P_FILE.

CALL FUNCTION 'GUI_UPLOAD'
  EXPORTING
    FILENAME                      = P_FILE1
   FILETYPE                      = 'ASC'
   HAS_FIELD_SEPARATOR           = 'X'
  TABLES
    DATA_TAB                      = IT_TAB.


INSERT   ZSTAFF_MASTER  FROM TABLE IT_TAB.
WRITE SY-SUBRC.