REPORT  Z.
* GET_TEXT IS A METHOD OF INTERFACE IF_MESSAGE
* GET_LONGTEXT IS A METHOD OF NTERFACE IF_MESSAGE
* CLASS CX_ROOT IMPLEMENTS THE INTERFACE IF_MESSAGE.
* KERNEL_ERRID IS AN ATTRIBUTE OF  CLASS CX_ROOT.
DATA ORF_1 TYPE REF TO CX_ROOT. "CX_ROOT IS A CLASS
DATA: NUM1 TYPE I,
      NUM2 TYPE I,
      RES  TYPE I.
PERFORM SETNUMBERS.
TRY.
    PERFORM DIVIDENUMBERS.
  CATCH CX_SY_ZERODIVIDE INTO ORF_1.
    WRITE 'Exception occurred'.
    WRITE / ORF_1->KERNEL_ERRID.
    WRITE / ORF_1->GET_TEXT( ).
    WRITE / ORF_1->GET_LONGTEXT( ).
ENDTRY.

PERFORM DISPLAYNUMBERS.

FORM SETNUMBERS.
  NUM1 = 10.
  NUM2 = 0.
ENDFORM.

FORM DIVIDENUMBERS RAISING CX_SY_ZERODIVIDE.
  RES = NUM1 / NUM2.
ENDFORM.

FORM DISPLAYNUMBERS.
  WRITE:/ 'Res is:' , RES.
ENDFORM.