REPORT  Z.
INTERFACE LIF_EMPLOYEE.
  METHODS
    SET_ATTRIBUTES
      IMPORTING IM_EMPLOYEE_NO   TYPE I
                IM_EMPLOYEE_NAME TYPE STRING
                IM_WAGE          TYPE I.
ENDINTERFACE.

CLASS EMPLOYEE DEFINITION.
  PUBLIC SECTION.
    INTERFACES LIF_EMPLOYEE.
    METHODS DISPLAY_ATTRIBUTES.
  PRIVATE SECTION.
    DATA: NO   TYPE I,
          NAME TYPE STRING,
          WAGE TYPE I.
ENDCLASS.
*-- CLASS LCL_CompanyEmployees IMPLEMENTATION
CLASS EMPLOYEE IMPLEMENTATION.
  METHOD LIF_EMPLOYEE~SET_ATTRIBUTES.
*   Adds a new employee to the list of employees
    NO   = IM_EMPLOYEE_NO.
    NAME = IM_EMPLOYEE_NAME.
    WAGE = IM_WAGE.
  ENDMETHOD.
  METHOD DISPLAY_ATTRIBUTES.
*   Displays all employees and there wage
    WRITE: / 'List of Employees'.
    WRITE: / NO, NAME, WAGE.
  ENDMETHOD.
ENDCLASS.

DATA EMPLOYEE1  TYPE REF TO EMPLOYEE.

START-OF-SELECTION.
* Create employee object
  CREATE OBJECT EMPLOYEE1.
  CALL METHOD EMPLOYEE1->LIF_EMPLOYEE~SET_ATTRIBUTES
    EXPORTING
      IM_EMPLOYEE_NO   = 1
      IM_EMPLOYEE_NAME = 'Karen Johnson'
      IM_WAGE          = 1250.
  CALL METHOD EMPLOYEE1->DISPLAY_ATTRIBUTES.