REPORT Z104329PGM1 NO STANDARD PAGE HEADING.
TYPES: BEGIN OF ITTYPE ,
         SALES    TYPE P DECIMALS 2,
         NAME(10) TYPE C,
       END OF ITTYPE.
DATA : IT TYPE STANDARD TABLE OF ITTYPE INITIAL SIZE 0,
       WA TYPE ITTYPE.
WA-SALES = 400. WA-NAME	= 'Jack'.
COLLECT WA INTO IT.

WA-SALES = 700. WA-NAME	= 'Jack'.
COLLECT WA INTO IT.

WA-SALES = 200. WA-NAME	= 'Jim'.
COLLECT WA INTO IT.

WA-SALES = 100. WA-NAME	= 'Jack'.
COLLECT WA INTO IT.

WA-SALES = 500. WA-NAME	= 'Jim'.
COLLECT WA INTO IT.

WA-SALES = 600. WA-NAME	= 'Jane'.
COLLECT WA INTO IT.

WA-SALES = 300. WA-NAME	= 'Jack'.
COLLECT WA INTO IT.

WA-SALES = 600. WA-NAME	= 'Jane'.
COLLECT WA INTO IT.

WA-SALES = 600. WA-NAME	= 'Jane'.
COLLECT WA INTO IT.

WA-SALES = 500. WA-NAME	= 'Jane'.
COLLECT WA INTO IT.


LOOP AT IT INTO WA.
  WRITE: /  WA-NAME, WA-SALES.
ENDLOOP.