REPORT Z104329PGM4 NO STANDARD PAGE HEADING.
*Non key components have to be numeric
TYPES: BEGIN OF FLIGHTTYPE,
         CARRID   TYPE SFLIGHT-CARRID,
         CONNID   TYPE SFLIGHT-CONNID,
         SEATSMAX TYPE SFLIGHT-SEATSMAX,
         SEATSOCC TYPE SFLIGHT-SEATSOCC,
       END OF FLIGHTTYPE.
DATA: ITSFLIGHT1 TYPE STANDARD TABLE OF FLIGHTTYPE
      INITIAL SIZE 0,
      ITSFLIGHT2 TYPE STANDARD TABLE OF FLIGHTTYPE
      INITIAL SIZE 0,
      WA1        TYPE FLIGHTTYPE,
      WA2        TYPE FLIGHTTYPE.

PERFORM SELECTFROMDB.
PERFORM COLLECTIT.
PERFORM DISPINTTABLE.

FORM SELECTFROMDB.
  SELECT CARRID CONNID SEATSMAX SEATSOCC
     FROM SFLIGHT
   INTO TABLE ITSFLIGHT1.
ENDFORM.

FORM COLLECTIT.
  LOOP AT ITSFLIGHT1 INTO WA1.
    COLLECT  WA1 INTO ITSFLIGHT2.
  ENDLOOP.
ENDFORM.

FORM DISPINTTABLE.
  LOOP AT ITSFLIGHT2 INTO WA2.
    WRITE:/ WA2-CARRID, WA2-CONNID,
    WA2-SEATSMAX, WA2-SEATSOCC.
  ENDLOOP.
ENDFORM.