REPORT Z.
*THIS COMMAND IS USED TO REMOVE SUPERFLUOUS SPACES FROM 
*A STRING.
*AFTER USING THE CONDENSE STATEMENT, 
*ALL THE WORDS IN THE STRING ARE SEPARATED BY 1 BLANK SPACE ONLY.

DATA : ALPHA(40) VALUE 'LETS  GET      ON-LINE   WHATSAY??'.
CONDENSE ALPHA.
WRITE ALPHA.
*WILL DISPLAY
*LETS GET ON-LINE WHATSAY??