REPORT Z.
*WITH THE NO-GAPS OPTION ALL THE BLANK SPACES 
*FROM THE STRING ARE REMOVED AND THE STRING IS 
*LEFT-JUSTIFIED.
DATA ALPHA(40) TYPE C.
ALPHA = '      LETS GET ON-LINE WHATSAY??'.
CONDENSE ALPHA NO-GAPS.
WRITE ALPHA.
*THIS WILL DISPLAY
*LETSGETON-LINEWHATSAY??