REPORT Z NO STANDARD PAGE HEADING.

TYPES: BEGIN OF SCARRTYPE,
         CARRID   TYPE SCARR-CARRID,
         CARRNAME TYPE S_CARRNAME,
         CURRCODE TYPE S_CURRCODE,
       END OF SCARRTYPE.

DATA ITSCARR  TYPE TABLE OF SCARRTYPE  INITIAL SIZE 0.
DATA WASCARR  TYPE SCARRTYPE.
DATA: FIELD_NAME(40) TYPE C, FIELD_VALUE(40) TYPE C.

START-OF-SELECTION.
  SELECT CARRID CARRNAME CURRCODE
    FROM SCARR
    INTO TABLE ITSCARR.

  LOOP AT ITSCARR INTO WASCARR.
    WRITE: / WASCARR-CARRID,WASCARR-CARRNAME,WASCARR-CURRCODE.
  ENDLOOP.

AT LINE-SELECTION.
  GET CURSOR FIELD FIELD_NAME VALUE FIELD_VALUE.
  CASE FIELD_NAME.
    WHEN 'WASCARR-CARRID'.
      WINDOW STARTING AT 5  80
             ENDING   AT 80  80.
    WHEN 'WASCARR-CARRNAME'.
      WINDOW STARTING AT 5  80
             ENDING   AT 120  80.
  ENDCASE.
  WRITE: 'FIELD_NAME:',  FIELD_NAME.
  WRITE: 'FIELD_VALUE:' ,FIELD_VALUE.