REPORT Z NO STANDARD PAGE HEADING.

TYPES: BEGIN OF SCARRTYPE,
         CARRID   TYPE SCARR-CARRID,
         CARRNAME TYPE S_CARRNAME,
         CURRCODE TYPE S_CURRCODE,
       END OF SCARRTYPE.

TYPES: BEGIN OF SPFLITYPE,
         CARRID   TYPE SPFLI-CARRID,
         CONNID   TYPE S_CONN_ID,
         CITYFROM TYPE S_FROM_CIT,
         CITYTO   TYPE S_TO_CITY,
       END OF SPFLITYPE.

TYPES: BEGIN OF SFLIGHTTYPE,
         CARRID    TYPE SFLIGHT-CARRID,
         CONNID    TYPE S_CONN_ID,
         FLDATE    TYPE S_DATE,
         PRICE     TYPE S_PRICE,
         PLANETYPE TYPE S_PLANETYE,
       END OF SFLIGHTTYPE.

DATA ITSCARR TYPE TABLE OF SCARRTYPE INITIAL SIZE 0.
DATA ITSPFLI TYPE TABLE OF SPFLITYPE INITIAL SIZE 0.
DATA ITSFLIGHT TYPE TABLE OF SFLIGHTTYPE   INITIAL SIZE 0.

DATA WASCARR TYPE SCARRTYPE.
DATA WASPFLI LIKE LINE OF ITSPFLI.
DATA WASFLIGHT TYPE SFLIGHTTYPE.
DATA: FIELD_NAME(40) TYPE C, 
      FIELD_VALUE(40) TYPE C.

TOP-OF-PAGE .
  WRITE 'Airline Details'.

TOP-OF-PAGE DURING LINE-SELECTION.
  IF SY-LSIND = 1.
    WINDOW STARTING AT 30 5
      ENDING  AT 80  30.
    WRITE 'SPFLI - Flight schedule'.
  ELSEIF  SY-LSIND = 2.
    WINDOW STARTING AT 85  5
     ENDING  AT 150  30.
    WRITE 'SFLIGHT - Flight Details'.
  ENDIF.

START-OF-SELECTION.
  SELECT CARRID CARRNAME CURRCODE
    FROM SCARR
    INTO TABLE ITSCARR.

  LOOP AT ITSCARR INTO WASCARR.
    WRITE: / WASCARR-CARRID,WASCARR-CARRNAME,WASCARR-CURRCODE.
    HIDE WASCARR-CARRID.
  ENDLOOP.

AT LINE-SELECTION.
  IF SY-LSIND = 1.
    GET CURSOR FIELD FIELD_NAME VALUE FIELD_VALUE.
    WRITE: 'FIELD_NAME:',  FIELD_NAME.
    WRITE: 'FIELD_VALUE:' ,FIELD_VALUE.
    IF FIELD_NAME = 'WASCARR-CARRID'.
      PERFORM SELECTFROMSPFLI.
    ELSE.
      MESSAGE E001(Z104329MSGCLASS) WITH 'Select field carrid'.
    ENDIF.
  ELSEIF SY-LSIND = 2.
    GET CURSOR FIELD FIELD_NAME VALUE FIELD_VALUE.
    WRITE : 'FIELD_NAME :',FIELD_NAME.
    WRITE : 'FIELD_VALUE:',FIELD_VALUE.
    IF NOT FIELD_NAME = 'WASPFLI-CONNID'. 
      MESSAGE E001(Z104329MSGCLAS) WITH 'Select field connid'.
    ELSE.
      PERFORM GETSFLIGHT.
      IF SY-SUBRC = 0.
         PERFORM DISPLAYSFLIGHT.
      ELSE.
         WRITE 'No Record IN SFLIGHT'.
      ENDIF.   
    ENDIF.
  ENDIF.

FORM  SELECTFROMSPFLI.
  PERFORM GETSPFLI.
  IF SY-SUBRC = 0.
    PERFORM DISPSPFLI.
  ELSE.
    WRITE 'No Record for SPFLI'.
  ENDIF.
ENDFORM.

FORM GETSPFLI.
  SELECT CARRID CONNID CITYFROM CITYTO
    INTO TABLE ITSPFLI FROM SPFLI
  WHERE CARRID = WASCARR-CARRID.
ENDFORM.

FORM DISPSPFLI.
  LOOP AT ITSPFLI INTO WASPFLI.
    WRITE:/ WASPFLI-CARRID , WASPFLI-CONNID ,WASPFLI-CITYFROM,
    WASPFLI-CITYTO.
    HIDE WASPFLI-CONNID.
  ENDLOOP.
ENDFORM.

FORM GETSFLIGHT.
  SELECT CARRID CONNID FLDATE PRICE PLANETYPE
    INTO TABLE ITSFLIGHT FROM SFLIGHT
  WHERE CARRID = WASCARR-CARRID AND CONNID = WASPFLI-CONNID.
ENDFORM.

FORM DISPLAYSFLIGHT.
  LOOP AT ITSFLIGHT INTO WASFLIGHT.
    WRITE:/ WASFLIGHT-CARRID , WASFLIGHT-CONNID ,WASFLIGHT-FLDATE,
    WASFLIGHT-PRICE, WASFLIGHT-PLANETYPE.
  ENDLOOP.
ENDFORM.