*Note: HIDE is not used here
REPORT Z NO STANDARD PAGE HEADING.

TYPES: BEGIN OF SCARRTYPE,
         CARRID   TYPE SCARR-CARRID,
         CARRNAME TYPE S_CARRNAME,
         CURRCODE TYPE S_CURRCODE,
       END OF SCARRTYPE.

TYPES: BEGIN OF SPFLITYPE,
         CARRID   TYPE SPFLI-CARRID,
         CONNID   TYPE S_CONN_ID,
         CITYFROM TYPE S_FROM_CIT,
         CITYTO   TYPE S_TO_CITY,
       END OF SPFLITYPE.

DATA ITSCARR TYPE TABLE OF SCARRTYPE INITIAL SIZE 0.
DATA ITSPFLI TYPE TABLE OF SPFLITYPE INITIAL SIZE 0.

DATA WASCARR TYPE SCARRTYPE.
DATA WASPFLI LIKE LINE OF ITSPFLI.
DATA: FIELD_NAME(40) TYPE C, 
      FIELD_VALUE(40) TYPE C.

START-OF-SELECTION.
  SELECT CARRID CARRNAME CURRCODE
    FROM SCARR
    INTO TABLE ITSCARR.

  LOOP AT ITSCARR INTO WASCARR.
    WRITE: / WASCARR-CARRNAME,WASCARR-CARRID, WASCARR-CURRCODE.
  ENDLOOP.

AT LINE-SELECTION.
  GET CURSOR FIELD FIELD_NAME VALUE FIELD_VALUE.
  WRITE: 'FIELD_NAME:',  FIELD_NAME.
  WRITE: 'FIELD_VALUE:' ,FIELD_VALUE.
  IF FIELD_NAME = 'WASCARR-CARRID'.
    PERFORM SELECTFROMSPFLI.
  ELSE.
    MESSAGE E001(Z104329MSGCLASS) WITH 'Select field carrid'.
  ENDIF.

FORM  SELECTFROMSPFLI.
  PERFORM GETSPFLI.
  IF SY-SUBRC = 0.
    PERFORM DISPSPFLI.
  ELSE.
    WRITE 'No Record for SPFLI'.
  ENDIF.
ENDFORM.

FORM GETSPFLI.
  SELECT CARRID CONNID CITYFROM CITYTO
    INTO TABLE ITSPFLI FROM SPFLI
  WHERE CARRID = FIELD_VALUE.
ENDFORM.

FORM DISPSPFLI.
  LOOP AT ITSPFLI INTO WASPFLI.
    WRITE:/ WASPFLI-CARRID , WASPFLI-CONNID ,WASPFLI-CITYFROM,
    WASPFLI-CITYTO.
  ENDLOOP.
ENDFORM.