*Pass Internal table as parameters
*Pass by value
REPORT Z NO STANDARD PAGE HEADING.
DATA ITAB TYPE TABLE OF I.

PERFORM FILLITAB.
WRITE: / 'Before invoking S1:'.
PERFORM DISPITAB.
PERFORM S1 USING ITAB.
WRITE: / 'After  invoking S1:'.
PERFORM DISPITAB.

FORM FILLITAB.
  DATA WA1 TYPE I."Local variable for workarea
  WA1 = 10. APPEND WA1 TO ITAB.
  WA1 = 20. APPEND WA1 TO ITAB.
  WA1 = 30. APPEND WA1 TO ITAB.
  WA1 = 40. APPEND WA1 TO ITAB.
ENDFORM.

FORM S1 USING VALUE(FITAB) LIKE ITAB.
  DATA WA2 TYPE I. "Local variable for workarea
  WA2 = 99.
  MODIFY FITAB FROM WA2 INDEX 3.
ENDFORM.

FORM DISPITAB.
  DATA WA3 TYPE I. "Local variable for workarea
  LOOP AT ITAB INTO WA3.
    WRITE WA3.
  ENDLOOP.
ENDFORM.