REPORT Z.
CLASS C1 DEFINITION.
  PUBLIC SECTION.
  METHODS T1.
ENDCLASS.

CLASS C2 DEFINITION.
 PUBLIC SECTION.
  METHODS T2.
ENDCLASS.

CLASS C1 IMPLEMENTATION.
    METHOD T1.
    WRITE:/5 'I AM T1, Method of class C1'.
    ENDMETHOD.
ENDCLASS.

CLASS C2 IMPLEMENTATION.
 METHOD T2.
    DATA O1 TYPE REF TO C1.
    CREATE OBJECT O1.
    CALL METHOD O1->T1.      
    WRITE:/5 'I AM T2, Method of class C2'.
 ENDMETHOD.
ENDCLASS.

START-OF-SELECTION.
DATA OREF2 TYPE REF TO C2.
CREATE OBJECT OREF2.
CALL METHOD OREF2->T2.