REPORT  Z.
*Non key components have to be numeric
TYPES: BEGIN OF FLIGHTTYPE,
         CARRID TYPE SFLIGHT-CARRID,
         CONNID TYPE SFLIGHT-CONNID ,
         SEATSMAX  TYPE SFLIGHT-SEATSMAX,
         SEATSOCC  TYPE SFLIGHT-SEATSOCC,
       END OF   FLIGHTTYPE.
DATA: ITSFLIGHT1 TYPE STANDARD TABLE OF FLIGHTTYPE
      INITIAL SIZE 0,
      ITSFLIGHT2 TYPE STANDARD TABLE OF FLIGHTTYPE
      INITIAL SIZE 4,
      WA1    TYPE  FLIGHTTYPE,
      WA2    TYPE  FLIGHTTYPE.

PERFORM SELECTFROMDB.
PERFORM APPENDIT.
PERFORM DISPINTTABLE.

FORM SELECTFROMDB.
  SELECT CARRID CONNID SEATSMAX SEATSOCC
      FROM SFLIGHT
    INTO TABLE ITSFLIGHT1.
ENDFORM.

FORM APPENDIT.
  LOOP AT ITSFLIGHT1 INTO WA1.
    APPEND  WA1 TO ITSFLIGHT2 SORTED BY PRICE. "<----
  ENDLOOP.
ENDFORM.

FORM DISPINTTABLE.
  LOOP AT ITSFLIGHT2 INTO WA2.
    WRITE:/ WA2-CARRID , WA2-CONNID,
    WA2-SEATSMAX , WA2-SEATSOCC.
  ENDLOOP.
ENDFORM.