REPORT  Z.
*Example of standard table
*INSERT IN STANDARD TABLE
DATA ITDEPT1 TYPE TABLE OF Z104329DEPT2
      WITH NON-UNIQUE DEFAULT KEY
      INITIAL SIZE 0.
DATA WA1 TYPE Z104329DEPT2.

DATA: ITDEPT2 TYPE TABLE OF Z104329DEPT2
      WITH NON-UNIQUE DEFAULT KEY
      INITIAL SIZE 0.

PERFORM SELECTFROMDB.
PERFORM ADDTOITDEPT2. 
PERFORM INSERT_INTO_INTTABLE.
PERFORM DISP.

FORM SELECTFROMDB.
  SELECT * FROM Z104329DEPT2 INTO TABLE ITDEPT1.
ENDFORM.

FORM INSERT_INTO_INTTABLE.
*1
INSERT LINES OF ITDEPT2 INTO TABLE ITDEPT1.
*55,66,77,88 and 99 are appended AT LAST
*NO INDEX CAN BE SPECIFIED HERE


*2
INSERT LINES OF ITDEPT2 FROM 2 TO 4 INTO TABLE ITDEPT1.
*66,77 and 88 are appended AT LAST
*NO INDEX CAN BE SPECIFIED HERE

*3
  INSERT LINES OF ITDEPT2 FROM 2 TO 4 INTO ITDEPT1 INDEX 2.
*66, 77 and 88 are inserted from index 2 in itdept1
ENDFORM.

FORM DISP.
  LOOP AT ITDEPT1 INTO WA1.
    WRITE :/ WA1-DEPTNO.
    WRITE :  WA1-DNAME.
    WRITE :  WA1-LOC.
  ENDLOOP.
ENDFORM.

FORM ADDTOITDEPT2.
  WA1-DEPTNO = 55. WA1-DNAME  = '55'.WA1-LOC    ='55'.
  APPEND WA1 TO ITDEPT2.

  WA1-DEPTNO = 66. WA1-DNAME  = '66'. WA1-LOC    ='66'.
  APPEND WA1 TO ITDEPT2.

  WA1-DEPTNO = 77. WA1-DNAME  = '77'. WA1-LOC    ='77'.
  APPEND WA1 TO ITDEPT2.

  WA1-DEPTNO = 88. WA1-DNAME  = '88'. WA1-LOC    ='88'.
  APPEND WA1 TO ITDEPT2.

  WA1-DEPTNO = 99. WA1-DNAME  = '99'. WA1-LOC    ='99'.
  APPEND WA1 TO ITDEPT2.
ENDFORM.