DATA DOJ   TYPE D VALUE '20211231'. "YYYYMMDD
DATA DOJ1  TYPE D.
DATA TIME  TYPE T   VALUE '235945'. "HHMMSS
DATA TIME1 TYPE T.  
DOJ1 = SY-DATUM. "SYSTEM DATE
TIME1 = SY-UZEIT. "SYSTEM TIME
WRITE: 'The Date is ', DOJ. "DDMMYYYYY
WRITE:/'The System Date is ', DOJ1. "DDMMYYYYY
WRITE:/'The Time is ', TIME. "HHMMSS
WRITE:/'The System Time is ', TIME1. "HHMMSS