REPORT  Z.
CLASS EMP DEFINITION.
  PUBLIC SECTION.
    METHODS SETEMP IMPORTING
                     IM_EMPNO TYPE N
                     IM_ENAME TYPE C.
    METHODS SETEMP IMPORTING
                     IM_EMPNO TYPE I 
                     IM_ENAME TYPE STRING.
    METHODS DISPEMP.
  PRIVATE SECTION.
    DATA: EMPNO(4)  TYPE N,
          ENAME(10) TYPE C.
ENDCLASS.

CLASS EMP IMPLEMENTATION.
  METHOD SETEMP.
    EMPNO = IM_EMPNO.
    ENAME = IM_ENAME.
  ENDMETHOD.
  METHOD DISPEMP.
    WRITE:/ 'Empno is:' , EMPNO.
    WRITE:/ 'Ename is:' , ENAME.
  ENDMETHOD.
ENDCLASS.

START-OF-SELECTION.
  DATA EMP1 TYPE REF TO EMP.
  DATA EMP2 TYPE REF TO EMP.

  CREATE OBJECT EMP1.
  EMP1->SETEMP( IM_EMPNO = 99 IM_ENAME = 'Ram' ).
  EMP1->DISPEMP( ).

  CREATE OBJECT EMP2.
  CALL METHOD EMP2->SETEMP
    EXPORTING
      IM_EMPNO = 100
      IM_ENAME = 'Shyam'.
  CALL METHOD EMP2->DISPEMP.
  "CALL METHOD emp2->dispemp( ).
  "emp2->dispemp( ).
