REPORT Z104329PGM3 NO STANDARD PAGE HEADING.
TYPES: BEGIN OF FLIGHTTYPE,
         CARRID   TYPE SFLIGHT-CARRID,
         CONNID   TYPE SFLIGHT-CONNID,
         SEATSMAX TYPE SFLIGHT-SEATSMAX,
         SEATSOCC TYPE SFLIGHT-SEATSOCC,
       END OF FLIGHTTYPE.
DATA: FLIGHTDATA TYPE  FLIGHTTYPE.
DATA: ITSFLIGHT TYPE STANDARD TABLE OF FLIGHTTYPE INITIAL SIZE 0.

SELECT CARRID CONNID SEATSMAX SEATSOCC
     FROM SFLIGHT INTO FLIGHTDATA.
     COLLECT  FLIGHTDATA INTO ITSFLIGHT.
ENDSELECT.

LOOP AT ITSFLIGHT INTO FLIGHTDATA .
  WRITE:/ FLIGHTDATA-CARRID, FLIGHTDATA-CONNID,
  FLIGHTDATA-SEATSMAX, FLIGHTDATA-SEATSOCC.
ENDLOOP.