TYPES: BEGIN OF FLIGHTTYPE,
         CARRID     TYPE SFLIGHT-CARRID,
         CONNID     TYPE SFLIGHT-CONNID,
         SEATSMAX   TYPE SFLIGHT-SEATSMAX,
         SEATSOCC   TYPE SFLIGHT-SEATSOCC,
       END OF   FLIGHTTYPE.
DATA: ITSFLIGHT1 TYPE STANDARD TABLE OF FLIGHTTYPE INITIAL SIZE 0,
      FLIGHTDATA TYPE  FLIGHTTYPE.

FLIGHTDATA-CARRID = 'AA'. FLIGHTDATA-CONNID = '17'. 
FLIGHTDATA-SEATSMAX = 385. FLIGHTDATA-SEATSOCC = 375.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '64'.
FLIGHTDATA-SEATSMAX = 380. FLIGHTDATA-SEATSOCC = 367.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'DL'. FLIGHTDATA-CONNID = '17'. 
FLIGHTDATA-SEATSMAX = 280. FLIGHTDATA-SEATSOCC = 271.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '64'. 
FLIGHTDATA-SEATSMAX = 220. FLIGHTDATA-SEATSOCC = 211.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AA'. FLIGHTDATA-CONNID = '17'. 
FLIGHTDATA-SEATSMAX = 280. FLIGHTDATA-SEATSOCC = 261.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'DL'. FLIGHTDATA-CONNID = '64'. 
FLIGHTDATA-SEATSMAX = 220. FLIGHTDATA-SEATSOCC = 213.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AA'. FLIGHTDATA-CONNID = '64'. 
FLIGHTDATA-SEATSMAX = 385. FLIGHTDATA-SEATSOCC = 371.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '17'.
FLIGHTDATA-SEATSMAX = 220. FLIGHTDATA-SEATSMAX = 200.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AA'. FLIGHTDATA-CONNID = '64'. 
FLIGHTDATA-SEATSMAX = 280. FLIGHTDATA-SEATSOCC = 271.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '17'. 
FLIGHTDATA-SEATSMAX = 380. FLIGHTDATA-SEATSOCC = 370.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'DL'. FLIGHTDATA-CONNID = '17'. 
FLIGHTDATA-SEATSMAX = 280. FLIGHTDATA-SEATSOCC = 270.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '64'. 
FLIGHTDATA-SEATSMAX = 380. FLIGHTDATA-SEATSOCC = 361.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'DL'. FLIGHTDATA-CONNID = '64'. 
FLIGHTDATA-SEATSMAX = 220. FLIGHTDATA-SEATSOCC = 213.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '64'.
FLIGHTDATA-SEATSMAX = 380. FLIGHTDATA-SEATSOCC = 361.
COLLECT FLIGHTDATA INTO ITSFLIGHT1.

LOOP AT ITSFLIGHT1 INTO FLIGHTDATA .
  WRITE:/ FLIGHTDATA-CARRID, FLIGHTDATA-CONNID,
  FLIGHTDATA-SEATSMAX, FLIGHTDATA-SEATSOCC.
ENDLOOP.