REPORT Z.
"Begin of Line lets all parameters
*appear on the same line
*When all parameters appear on same line we cannot
*see parameter labels
*Hence, need to give COMMENT

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(12)  TEXTA FOR FIELD FNAME.
PARAMETERS FNAME(7)  TYPE C.
SELECTION-SCREEN COMMENT 28(12) TEXTB FOR FIELD MNAME.
PARAMETERS MNAME(7)  TYPE C.
SELECTION-SCREEN COMMENT 48(12) TEXTC FOR FIELD LNAME.
PARAMETERS LNAME(10) TYPE C.
SELECTION-SCREEN END OF LINE.

INITIALIZATION.
  TEXTA = 'First  Name'.
  TEXTB = 'Middle Name'.
  TEXTC = 'Last   Name'.

START-OF-SELECTION.
  WRITE:/  FNAME , MNAME, LNAME.

