REPORT  Z.
TYPES : BEGIN OF TYSCARR,
        CARRID  TYPE SCARR-CARRID,
        CARRNAME TYPE SCARR-CARRNAME,
        CURRCODE   TYPE SCARR-CURRCODE,
 END OF TYSCARR.

DATA ITSCARR TYPE SORTED TABLE OF TYSCARR
      WITH UNIQUE KEY CARRNAME INITIAL SIZE 0.
DATA WA TYPE TYSCARR.

PERFORM SELECTFROMDB.
PERFORM DISPINTTABLE.

FORM SELECTFROMDB.
  SELECT CARRID CARRNAME CURRCODE
      FROM SCARR
    INTO TABLE ITSCARR.
ENDFORM.


FORM DISPINTTABLE.
  LOOP AT ITSCARR INTO WA.
    WRITE:/ WA-CARRID , WA-CARRNAME,WA-CURRCODE.
   ENDLOOP.

ENDFORM.