REPORT Z104329PGM4 NO STANDARD PAGE HEADING.
TYPES: BEGIN OF FLIGHTTYPE,
         FLDATE    TYPE SFLIGHT-FLDATE,
         PLANETYPE TYPE SFLIGHT-PLANETYPE,
         CARRID    TYPE SFLIGHT-CARRID,
         CONNID    TYPE SFLIGHT-CONNID,
         SEATSMAX  TYPE SFLIGHT-SEATSMAX,
         SEATSOCC  TYPE SFLIGHT-SEATSOCC,
       END OF   FLIGHTTYPE.
DATA: ITSFLIGHT TYPE STANDARD TABLE OF FLIGHTTYPE
      INITIAL SIZE 0,
      WA        TYPE  FLIGHTTYPE.

*PERFORM SELECTFROMDB.
SORT ITSFLIGHT BY CARRID.
PERFORM DISPFIRST.
SELECT FLDATE PLANETYPE CARRID CONNID SEATSMAX SEATSOCC UP TO 160 ROWS
      FROM SFLIGHT
    INTO  WA.
*AT NEW CARRID.
  ON CHANGE OF WA-CARRID.
    WRITE : / 'Carrid:', WA-CARRID.
  ENDON.
*ENDAT.
  PERFORM DISPRESTFIELDS.
ENDSELECT.
PERFORM  DISPLAST.
SKIP.

FORM SELECTFROMDB.
  SELECT FLDATE PLANETYPE CARRID CONNID SEATSMAX SEATSOCC UP TO 160 ROWS
      FROM SFLIGHT
    INTO TABLE ITSFLIGHT.
ENDFORM.

FORM DISPFIRST.
  WRITE: /'Carrid',
          12 'Connid',
          25 'Flightdate',
          45 'Plane Type',
          65 'Seats Maximum',
          85 'Seats Occupied'.

  ULINE.
ENDFORM.

FORM DISPRESTFIELDS.
  WRITE:  /12 WA-CONNID,
          25 WA-FLDATE,
          45 WA-PLANETYPE,
          65 WA-SEATSMAX,
          85 WA-SEATSOCC.
ENDFORM.

FORM DISPLAST.
  WRITE: /  '--------',
            12 '------',
            25 '----------',
            45 '---------',
            65 '---------',
            85 '---------'.

ENDFORM.