REPORT Z.
PARAMETERS: NUM1 TYPE I DEFAULT 10,
            NUM2 TYPE I DEFAULT 20,
            NUM3 TYPE P DECIMALS 2 DEFAULT '12.45'.
DATA RES TYPE I.

*PERFORM ADD USING NUM1 NUM2 CHANGING RES.
PERFORM ADD USING NUM1 NUM3 CHANGING RES.
WRITE: / 'The result is:',RES.

*FORM ADD USING VALUE(N1) VALUE(N2) R.
*R = N1 + N2.
*ENDFORM.

FORM ADD USING VALUE(N1) TYPE I VALUE(N2) TYPE I CHANGING R.
    R = N1 + N2.
ENDFORM.