TYPES: BEGIN OF TYSCARR,
        MANDT(3)    TYPE C,
        CARRID(3)   TYPE C,
        CARRNAME(20) TYPE C,
        CURRCODE(3) TYPE C,
       END OF TYSCARR.

DATA ITSCARR TYPE TABLE OF TYSCARR.
DATA WA TYPE TYSCARR.

WA-MANDT = SY-MANDT.

WA-CARRID = 'AA'. WA-CARRNAME = 'American Airlines'.
WA-CURRCODE = 'USD'.
APPEND WA TO ITSCARR.

WA-CARRID = 'AB'. WA-CARRNAME = 'Air Berlin'.
WA-CURRCODE = 'EUR'.
APPEND WA TO ITSCARR.

WA-CARRID = 'AC'. WA-CARRNAME = 'Air Canada'.
WA-CURRCODE = 'CAD'.
APPEND WA TO ITSCARR.

WA-CARRID = 'AF'. WA-CARRNAME = 'Air France'.
WA-CURRCODE = 'EUR'.
APPEND WA TO ITSCARR.

LOOP AT ITSCARR INTO WA.
  WRITE : / SY-TABIX , WA-MANDT  , WA-CARRID ,
  WA-CARRNAME , WA-CURRCODE.
ENDLOOP.