REPORT  Z.
DATA: T(10) TYPE C VALUE 'abcdefghij',
       VAR LIKE T.

VAR = T.
WRITE VAR.

SHIFT VAR. "SHIFT BY ONE PLACE LEFT bcdefghij
WRITE / VAR.

VAR = T. "VAR NOW CONTAINS abcdefghij
SHIFT VAR BY 3 PLACES LEFT. "defghij
WRITE / VAR.

VAR = T. "VAR NOW CONTAINS abcdefghij
SHIFT VAR BY 3 PLACES RIGHT. "   abcdefg
WRITE / VAR.
**
VAR = T.
SHIFT VAR BY 3 PLACES CIRCULAR.
WRITE / VAR.


