REPORT Z.
DATA: LENGTH(2)         TYPE P VALUE 0.
PARAMETERS STRING(30)    	TYPE C DEFAULT  'testwhile'.

WHILE STRING NE SPACE.
  WRITE / STRING(1).
  LENGTH = LENGTH + 1.
  SHIFT STRING.
ENDWHILE.
WRITE: / 'Length of character string: ', LENGTH.