REPORT Z.

TYPES: BEGIN OF WA,
         FLDATE TYPE SBOOK-FLDATE,
         AVG    TYPE SBOOK-LOCCURAM,
       END OF WA.
DATA   ITAB TYPE TABLE OF WA WITH EMPTY KEY.

SELECT FLDATE, AVG( LOCCURAM ) AS AVG
       FROM SBOOK
       WHERE SBOOK~CARRID = 'LH' AND
             SBOOK~CONNID = '0400'
       GROUP BY FLDATE
       ORDER BY AVG DESCENDING
       INTO CORRESPONDING FIELDS OF TABLE @ITAB.

CL_DEMO_OUTPUT=>DISPLAY( ITAB ).