REPORT Z.

TYPES BEGIN OF STRUCTURE.
TYPES CARRNAME TYPE SCARR-CARRNAME.
INCLUDE TYPE SPFLI AS SPFLI.
TYPES URL TYPE SCARR-URL.
TYPES END OF STRUCTURE.

DATA ITAB TYPE STANDARD TABLE OF STRUCTURE WITH EMPTY KEY.

SELECT SCARR~CARRNAME, SPFLI~*, SCARR~URL
       FROM SCARR INNER JOIN SPFLI ON SCARR~CARRID = SPFLI~CARRID
       INTO TABLE @ITAB.

CL_DEMO_OUTPUT=>DISPLAY( ITAB ).