REPORT Z104329PGM2 NO STANDARD PAGE HEADING.

TYPES: BEGIN OF FLIGHTTYPE,
         CARRID    TYPE SFLIGHT-CARRID,
         CONNID    TYPE SFLIGHT-CONNID,
         FLDATE    TYPE SFLIGHT-FLDATE,
         PLANETYPE TYPE SFLIGHT-PLANETYPE,
         SEATSMAX  TYPE SFLIGHT-SEATSMAX,
         SEATSOCC  TYPE SFLIGHT-SEATSOCC,
       END OF   FLIGHTTYPE.
DATA: ITSFLIGHT TYPE STANDARD TABLE OF FLIGHTTYPE INITIAL SIZE 0,
      WA        TYPE  FLIGHTTYPE.

PERFORM SELECTFROMDB.

LOOP AT ITSFLIGHT INTO WA.
  AT FIRST.
    PERFORM DISPFIRST.
  ENDAT.
  PERFORM DISPALLFIELDS.
  AT LAST.
    PERFORM DISPLAST.
  ENDAT.
ENDLOOP.

FORM SELECTFROMDB.
  SELECT CARRID CONNID FLDATE PLANETYPE SEATSMAX SEATSOCC UP TO 4 ROWS
      FROM SFLIGHT
    INTO TABLE ITSFLIGHT.
ENDFORM.

FORM DISPFIRST.
  FORMAT COLOR 5.
  WRITE: /  'Carrid',
           12 'Connid',
           25 'Flightdate',
           45 'Plane Type',
           65 'Seats Maximum',
           85 'Seats Occupied'.
  ULINE.
  FORMAT COLOR OFF.
ENDFORM.

FORM DISPALLFIELDS.
  WRITE : / WA-CARRID ,
          12 WA-CONNID,
          25 WA-FLDATE,
          45 WA-PLANETYPE,
          65 WA-SEATSMAX,
          85 WA-SEATSOCC.
ENDFORM.

FORM DISPLAST.
  WRITE: /  '--------',
           12 '------',
           25 '----------',
           45 '---------',
           70 '-----',
           90 '-----'.
ENDFORM.