REPORT Z NO STANDARD PAGE HEADING.
TYPES: BEGIN OF TYAIRLINES,
         SCCARRID    TYPE SCARR-CARRID,
         CARRNAME    TYPE SCARR-CARRNAME,
         SPCARRID    TYPE SPFLI-CARRID,
         CONNID      TYPE SPFLI-CONNID,
         COUNTRYFROM TYPE SPFLI-COUNTRYFR,
         COUNTRYTO   TYPE SPFLI-COUNTRYTO,
       END OF TYAIRLINES.

DATA ITAIRLINES TYPE STANDARD TABLE OF TYAIRLINES.
DATA WAAIRLINES LIKE LINE OF ITAIRLINES.

SELECT SC~CARRID SC~CARRNAME
  SP~CARRID SP~CONNID SP~COUNTRYFR SP~COUNTRYTO
   INTO TABLE ITAIRLINES
  FROM SPFLI AS SP
  LEFT OUTER JOIN
  SCARR AS SC
  ON SC~CARRID = SP~CARRID.

LOOP AT  ITAIRLINES INTO WAAIRLINES.
  PERFORM DISP.
ENDLOOP.
SKIP.

FORM DISP.
  WRITE : / WAAIRLINES-SCCARRID ,
              9 WAAIRLINES-CARRNAME,
              38 WAAIRLINES-SPCARRID ,
             58 WAAIRLINES-CONNID,
             68 WAAIRLINES-COUNTRYFROM,
             88 WAAIRLINES-COUNTRYTO.
ENDFORM.