REPORT Z  NO STANDARD PAGE HEADING LINE-COUNT 5.
START-OF-SELECTION.
  DO 5 TIMES.
    WRITE: / '1', / '2', / '3' , / '4' , /'5'.
  ENDDO.

TOP-OF-PAGE.
  WRITE: 'In TOP:' .

END-OF-PAGE.
  WRITE: 'In EOP:' , SY-PAGNO.