REPORT Z104329PGM1.
DATA: TEXT TYPE STRING VALUE '0123456789ABCDEF',
      COLUMN  TYPE I VALUE 25,
      LENGTH  TYPE I VALUE 5.

WRITE TEXT.
WRITE /5 TEXT.
WRITE (10) TEXT.
WRITE /5(10) TEXT.
WRITE AT /COLUMN TEXT. 
WRITE AT /LENGTH TEXT.
WRITE AT /COLUMN(LENGTH) TEXT. 