" Use the statements READ LINE and READ CURRENT LINE to read data from the lines of existing list levels. These statements are closely connected to the HIDE technique.

" All of the lists generated by a single program are stored internally in the system. You can therefore access any list in a program that was created for the same screen and that has not yet been deleted by returning to a lower list level. To read lines, use the statements READ LINE and READ CURRENT LINE.

" To read a line from a list after an interactive list event, use the READ LINE statement:

" READ LINE <lin> [INDEX <idx>]

" [FIELD VALUE <f1> [INTO <g 1>] ... <f n> [INTO <g n>]]

" [OF CURRENT PAGE|OF PAGE <p>].

" The statement without any options stores the contents of line <lin> from the list on which the event was triggered (index SY-LILLI) in the SY-LISEL system field and fills all HIDE information stored for this line back into the corresponding fields. As far as SY-LISEL and the HIDE area are concerned, READ LINE has the same effect as an interactive line selection.

" If the selected line <lin> exists, the system sets SY-SUBRC to 0, otherwise to 4.

" The options have the following effects:

" INDEX <idx>

" FIELD VALUE <f 1 > [INTO <g 1 >] ... <f n> [INTO <g n>]

" OF CURRENT PAGE

" OF PAGE <p>

" Look at the demo program <b>demo_list_read_line</b>

REPORT  Z NO STANDARD PAGE HEADING LINE-COUNT 5.
TYPES: BEGIN OF TYSFLIGHT,
         CARRID TYPE SFLIGHT-CARRID,
         CONNID TYPE SFLIGHT-CONNID,
         FLDATE TYPE SFLIGHT-FLDATE,
       END OF TYSFLIGHT.
DATA ITSFLIGHT TYPE TABLE OF TYSFLIGHT.
DATA WASFLIGHT TYPE TYSFLIGHT.
DATA WA TYPE SFLIGHT-CARRID.
DATA WA1 TYPE SFLIGHT-CONNID.
DATA WA2 TYPE SFLIGHT-FLDATE.

TOP-OF-PAGE.
  WRITE: 'Page no:' , SY-PAGNO.

START-OF-SELECTION.
  SELECT CARRID CONNID FLDATE FROM SFLIGHT INTO
  TABLE ITSFLIGHT.
  LOOP AT  ITSFLIGHT INTO WASFLIGHT.
    WRITE :/ WASFLIGHT-CARRID, WASFLIGHT-CONNID ,
             WASFLIGHT-FLDATE.
  ENDLOOP.

AT LINE-SELECTION.
  PERFORM READCURRENTLINE.
  PERFORM READLINEOFPAGE.
  PERFORM READSPECIFICLINE.
  Read line SY-CUROW field value wa.

WRITE:/'WA:', WA.
WRITE:/'WA1:', WA1.
WRITE:/'WA2:', WA2.

FORM READCURRENTLINE.
  READ CURRENT LINE FIELD VALUE
     WASFLIGHT-CARRID INTO WA
     WASFLIGHT-CONNID INTO WA1
     WASFLIGHT-FLDATE INTO WA2.
ENDFORM.

FORM READLINEOFPAGE.
  READ LINE 2 OF PAGE 3 FIELD VALUE
      WASFLIGHT-CARRID INTO WA
      WASFLIGHT-CONNID INTO WA1
      WASFLIGHT-FLDATE INTO WA2.
ENDFORM.


FORM READSPECIFICLINE.
  READ LINE 3 FIELD VALUE WASFLIGHT-CARRID INTO WA.
  READ LINE 3 FIELD VALUE WASFLIGHT-CONNID INTO WA1.
  READ LINE 3 FIELD VALUE WASFLIGHT-FLDATE INTO WA2.
ENDFORM.