REPORT Z.
PARAMETERS PEMPNO TYPE Z104329EMP-EMPNO.

DATA: BEGIN OF FSEMP,
       EMPNO TYPE Z104329EMP-EMPNO,
       ENAME TYPE Z104329EMP-ENAME,
   END OF FSEMP.

" 1. Classical method
SELECT EMPNO ENAME
  FROM Z104329EMP
  INTO FSEMP
WHERE EMPNO = PEMPNO.
WRITE: FSEMP-EMPNO, FSEMP-ENAME.
ENDSELECT.

" 2 New open SQL
SELECT EMPNO, ENAME
  FROM Z104329EMP
  INTO @FSEMP
WHERE EMPNO = @PEMPNO.
WRITE: FSEMP-EMPNO, FSEMP-ENAME.
ENDSELECT.

" 3 New open SQL - FSEMP Need not be declared beforehand
SELECT EMPNO, ENAME
  FROM Z104329EMP
  INTO @DATA(FSEMP)
WHERE EMPNO = @PEMPNO.
WRITE: FSEMP-EMPNO, FSEMP-ENAME.
ENDSELECT.