REPORT Z.
TYPES: BEGIN OF IT_TABTYPE,
         MATNR(18),
         MBRSH(1),
         MTART(4),
         MAKTX(40),
         MEINS(3),
         MATKL(9),
       END OF IT_TABTYPE.

DATA IT_TAB TYPE TABLE OF IT_TABTYPE INITIAL SIZE 0.
DATA WA TYPE IT_TABTYPE.

START-OF-SELECTION.
  DATA P_FILE1 TYPE STRING.
  P_FILE1 = 'D:\MATMAST.TXT'.

  CALL FUNCTION 'GUI_UPLOAD'
    EXPORTING
      FILENAME            = P_FILE1
      FILETYPE            = 'ASC'
      HAS_FIELD_SEPARATOR = 'X'
    TABLES
      DATA_TAB            = IT_TAB.

  WRITE: 'SY-SUBRC IS:', SY-SUBRC.
  SKIP 1.
  LOOP AT IT_TAB INTO WA.
    WRITE WA-MATNR.
    WRITE WA-MBRSH.
    WRITE WA-MTART.
    WRITE WA-MAKTX.
    WRITE WA-MEINS.
    WRITE WA-MATKL.
  ENDLOOP.
  IF SY-SUBRC <> 0.
* Implement suit_table error handling here
  ENDIF.
  OPEN DATASET 'VKFILE1' FOR OUTPUT IN TEXT  MODE ENCODING DEFAULT.
  LOOP AT IT_TAB INTO WA.
    TRANSFER WA TO 'VKFILE1'.
    CLEAR WA.
  ENDLOOP.

  CLOSE DATASET 'VKFILE1'.