REPORT Z.
TYPES: BEGIN OF FLIGHTTYPE,
         CARRID TYPE SFLIGHT-CARRID,
         CONNID TYPE SFLIGHT-CONNID ,
         PRICE  TYPE SFLIGHT-PRICE,
         SEATSOCC  TYPE SFLIGHT-SEATSOCC,
       END OF   FLIGHTTYPE.
DATA: ITSFLIGHT TYPE SORTED TABLE OF FLIGHTTYPE
      WITH NON-UNIQUE KEY CARRID CONNID INITIAL SIZE 0,
      WA TYPE  FLIGHTTYPE.

PERFORM SELECTFROMDB.
PERFORM DISPINTTABLE.

FORM SELECTFROMDB.
  SELECT CARRID CONNID PRICE  SEATSOCC UP TO 15 ROWS
      FROM SFLIGHT
    INTO TABLE ITSFLIGHT.
ENDFORM.

FORM DISPINTTABLE.
  LOOP AT ITSFLIGHT INTO WA.
    WRITE:/ WA-CARRID , WA-CONNID,
    WA-PRICE , WA-SEATSOCC.
  ENDLOOP.
ENDFORM.