REPORT Z.
"CAN USE EITHER INSERT OR APPEND FOR SORTED TABLE
"Key must be specified  for sorted table
"Key can be unique or non-unique
TYPES: BEGIN OF TYSCARR,
         MANDT    TYPE SCARR-MANDT,
         CARRID   TYPE SCARR-CARRID,
         CARRNAME TYPE SCARR-CARRNAME,
         CURRCODE TYPE SCARR-CURRCODE,
       END OF TYSCARR.

DATA ITSCARR TYPE SORTED TABLE OF TYSCARR WITH UNIQUE KEY CARRID.
DATA WA TYPE TYSCARR.

WA-MANDT = SY-MANDT.

WA-CARRID = 'AA'. WA-CARRNAME = 'American Airlines'. WA-CURRCODE = 'USD'.
APPEND WA TO ITSCARR.

WA-CARRID = 'AB'. WA-CARRNAME = 'Air Berlin'. WA-CURRCODE = 'EUR'.
INSERT  WA INTO TABLE ITSCARR.

WA-CARRID = 'AC'. WA-CARRNAME = 'Air Can'. WA-CURRCODE = 'CAD'.
APPEND WA TO ITSCARR.

WA-CARRID = 'AF'. WA-CARRNAME = 'Air France'. WA-CURRCODE = 'EUR'.
INSERT  WA INTO TABLE ITSCARR.

LOOP AT ITSCARR INTO WA.
  WRITE : / SY-TABIX , WA-MANDT  , WA-CARRID ,
  WA-CARRNAME , WA-CURRCODE.
ENDLOOP.