TYPES: BEGIN OF TYSCARR,
        MANDT    TYPE SCARR-MANDT,
        CARRID   TYPE SCARR-CARRID,
        CARRNAME TYPE SCARR-CARRNAME,
        CURRCODE TYPE SCARR-CURRCODE,
       END OF TYSCARR.

DATA ITSCARR TYPE TABLE OF TYSCARR.
DATA WA TYPE TYSCARR.

WA-MANDT = SY-MANDT.

WA-CARRID = 'AA'. WA-CARRNAME = 'American Airlines'.
WA-CURRCODE = 'USD'.
APPEND WA TO ITSCARR.

WA-CARRID = 'AB'. WA-CARRNAME = 'Air Berlin'.
WA-CURRCODE = 'EUR'.
APPEND WA TO ITSCARR.

WA-CARRID = 'AC'. WA-CARRNAME = 'Air Canada'.
WA-CURRCODE = 'CAD'.
APPEND WA TO ITSCARR.

WA-CARRID = 'AF'. WA-CARRNAME = 'Air France'.
WA-CURRCODE = 'EUR'.
APPEND WA TO ITSCARR.
CLEAR WA.

READ TABLE ITSCARR TRANSPORTING CARRID 
  INTO WA WITH
  "KEY CARRID = 'AA'.
  " KEY CURRCODE = 'USD'. "First occurence of USD
   KEY CARRID = 'AA' CARRNAME = 'American Airlines'.
     "Above implies AND
WRITE: 'SY-SUBRC IS :' , SY-SUBRC.
  IF SY-SUBRC = 0.
      WRITE: /'Carrid is' , WA-CARRID,
          'Carrname is',WA-CARRNAME,
          'Currcode is',WA-CURRCODE.
  ELSE.
    WRITE 'Record not present'.
  ENDIF.
