*CREATE_FOR_CDS_VIEW is a static method of the class CL_SALV_GUI_TABLE_IDA
*If the parameters of the create method are observed, it is seen
*that it has a Returning parameter RO_ALV_GUI_TABLE_IDA
*RO_ALV_GUI_TABLE_IDA IS OF TYPE IF_SALV_GUI_TABLE_IDA.

*IF_SALV_GUI_TABLE_IDA IS AN INTERFACE WHICH HAS THE METHOD DISPLAY OPTIONS
* DISPLAY OPTIONS RETURNS AN WITH THE NAME RO_DISPLAY_OPTIONS
* RO_DISPLAY_OPTIONS IS OF TYPE IF_SALV_GUI_TABLE_DISPLAY_OPT
*IF_SALV_GUI_TABLE_DISPLAY_OPT IS AN INTERFACE WHICH HAS METHOD SET_TITLE
* IT ALSO HAS THE METHOD ENABLE_ALTERNATING_ROW_PATTERN

*IF_SALV_GUI_TABLE_IDA IS AN INTERFACE WHICH HAS THE METHOD FULLSCREEN.

*METHOD FULLSCREEN RETURNS OBJECT OF TYPE IF_SALV_GUI_FULLSCREEN_IDA

*IF_SALV_GUI_TABLE_IDA IS AN INTERFACE WHICH HAS THE METHOD FIELD_CATALOG.
*METHOD FIELD_CATALOG RETURNS AN OBJECT OF WITH THE NAME RO_FIELD_CATALOG
*RO_FIELD_CATALOG IS OF TYPE IF_SALV_GUI_FIELD_CATALOG_IDA
*i.e METHOD FIELD_CATALOG RETURNS AN OBJECT OF TYPE IF_SALV_GUI_FIELD_CATALOG_IDA
* IF_SALV_GUI_FIELD_CATALOG_IDA HAS THE METHOD GET_AVAILABLE_FIELDS
* IF_SALV_GUI_FIELD_CATALOG_IDA HAS THE METHOD SET_AVAILABLE_FIELDS
*IF_SALV_GUI_FULLSCREEN_IDA IS AN INTERFACE WHICH HAS THE METHOD DISPLAY.

REPORT Z.

CL_SALV_GUI_TABLE_IDA=>CREATE_FOR_CDS_VIEW(
  EXPORTING
    IV_CDS_VIEW_NAME               = 'ZVK_CDS2_EMP'
  RECEIVING
    RO_ALV_GUI_TABLE_IDA           = DATA(O_ALV)
).
*
*To set title
O_ALV->DISPLAY_OPTIONS( )->SET_TITLE( IV_TITLE = 'List of Employees' ).
O_ALV->DISPLAY_OPTIONS( )->ENABLE_ALTERNATING_ROW_PATTERN( )."Zebra layout

*O_ALV->DEFAULT_LAYOUT( )->SET_SORT_ORDER(
*                          VALUE #( ( FIELD_NAME = 'DEPTNO'  ) ) ).

O_ALV->DEFAULT_LAYOUT( )->SET_SORT_ORDER(
                          VALUE #( ( FIELD_NAME = 'DEPTNO' DESCENDING  = ABAP_TRUE  ) ) ).


*O_ALV->DEFAULT_LAYOUT( )->SET_SORT_ORDER(
*                          VALUE #( ( FIELD_NAME = 'DEPTNO' IS_GROUPED  = ABAP_TRUE ) ) ).

"O_ALV->DEFAULT_LAYOUT( )->SET_SORT_ORDER(
"                          VALUE #( ( FIELD_NAME = 'DEPTNO' IS_GROUPED  = ABAP_TRUE DESCENDING  = ABAP_TRUE ) ) ).
**
**"To remove print and aggregation button from the custom alv toolbar
**

O_ALV->STANDARD_FUNCTIONS( )->SET_PRINT_ACTIVE( IV_ACTIVE = ABAP_FALSE ).
O_ALV->STANDARD_FUNCTIONS( )->SET_AGGREGATION_ACTIVE( IV_ACTIVE = ABAP_FALSE ).

DATA(O_FUL_SCRN) = O_ALV->FULLSCREEN( ).
O_FUL_SCRN->DISPLAY( ).