REPORT Z.
*CREATE_FOR_CDS_VIEW is a static method of the class CL_SALV_GUI_TABLE_IDA
*If the parameters of the CREATE_FOR_CDS_VIEW method are observed, it is seen
*that it has a Returning parameter RO_ALV_GUI_TABLE_IDA
*RO_ALV_GUI_TABLE_IDA IS OF TYPE IF_SALV_GUI_TABLE_IDA.

*IF_SALV_GUI_TABLE_IDA IS AN INTERFACE WHICH HAS THE METHOD FULLSCREEN.
*METHOD FULLSCREEN RETURNS OBJECT OF TYPE IF_SALV_GUI_FULLSCREEN_IDA

*IF_SALV_GUI_TABLE_IDA IS AN INTERFACE WHICH HAS THE METHOD FIELD_CATALOG.
*METHOD FIELD_CATALOG RETURNS AN OBJECT OF WITH THE NAME RO_FIELD_CATALOG
*RO_FIELD_CATALOG IS OF TYPE IF_SALV_GUI_FIELD_CATALOG_IDA
*i.e METHOD FIELD_CATALOG RETURNS AN OBJECT OF TYPE IF_SALV_GUI_FIELD_CATALOG_IDA
* IF_SALV_GUI_FIELD_CATALOG_IDA HAS THE METHOD GET_AVAILABLE_FIELDS


*IF_SALV_GUI_FIELD_CATALOG_IDA HAS THE METHOD SET_AVAILABLE_FIELDS
*IF_SALV_GUI_FULLSCREEN_IDA IS AN INTERFACE WHICH HAS THE METHOD DISPLAY.

CL_SALV_GUI_TABLE_IDA=>CREATE_FOR_CDS_VIEW(
  EXPORTING
    IV_CDS_VIEW_NAME               = 'ZVK_CDS2_EMP'
  RECEIVING
    RO_ALV_GUI_TABLE_IDA           = DATA(O_ALV)
).


DATA(O_FCAT) = O_ALV->FIELD_CATALOG( ).
*METHOD FIELD_CATALOG RETURNS AN OBJECT OF WITH THE NAME RO_FIELD_CATALOG
*IF_SALV_GUI_FIELD_CATALOG_IDA HAS THE METHOD GET_AVAILABLE_FIELDS
* Observe the parameter of the method GET_AVAILABLE_FIELDS
* The parameter name is ETS_FIELD_NAMES
* ETS_FIELD_NAMES is of type IF_SALV_GUI_TYPES_IDA=>YTS_FIELD_NAME
* IF_SALV_GUI_TYPES_IDA is an interface which has the type YTS_FIELD_NAME
*  yts_field_name is a sorted table of fieldname with unique key table_line .

"Get total no.of fields
O_FCAT->GET_AVAILABLE_FIELDS(
  IMPORTING
    ETS_FIELD_NAMES = DATA(IT_FIELDS)
).
*
*"Delete one field
**though the view has SAL it will still not appear in the alv
*
DELETE IT_FIELDS WHERE TABLE_LINE = 'SAL'.
DELETE IT_FIELDS WHERE TABLE_LINE = 'HIREDATE'.

O_FCAT->SET_AVAILABLE_FIELDS( ITS_FIELD_NAMES = IT_FIELDS ).

O_FCAT->SET_FIELD_HEADER_TEXTS(
  EXPORTING
    IV_FIELD_NAME                  = 'EMPNO'
    IV_HEADER_TEXT                 = 'Employee Num'
    IV_TOOLTIP_TEXT                = 'This is emp no'
    IV_TOOLTIP_TEXT_LONG           =  'This is emp no field'
).

O_FCAT->SET_FIELD_HEADER_TEXTS(
  EXPORTING
    IV_FIELD_NAME                  = 'ENAME'
    IV_HEADER_TEXT                 = 'Employee Name'
*     IV_TOOLTIP_TEXT                =
*     IV_TOOLTIP_TEXT_LONG           =
).


O_FCAT->SET_FIELD_HEADER_TEXTS(
  EXPORTING
    IV_FIELD_NAME                  = 'DEPTNO'
    IV_HEADER_TEXT                 = 'Department Num').

O_FCAT->SET_FIELD_HEADER_TEXTS(
  EXPORTING
    IV_FIELD_NAME                  = 'JOB'
    IV_HEADER_TEXT                 = 'Job Details').

O_FCAT->SET_FIELD_HEADER_TEXTS(
  EXPORTING
    IV_FIELD_NAME                  = 'MGR'
    IV_HEADER_TEXT                 = 'Manager Empno').

DATA(O_FUL_SCRN) = O_ALV->FULLSCREEN( ).
O_FUL_SCRN->DISPLAY( ).