* SY-LISEL comparison does not work properly

REPORT Z NO STANDARD PAGE HEADING.
TYPES: BEGIN OF SCARRTYPE,
         CARRNAME TYPE S_CARRNAME,
         CARRID   TYPE SCARR-CARRID,
         CURRCODE TYPE S_CURRCODE,
       END OF SCARRTYPE.

TYPES: BEGIN OF SPFLITYPE,
         CARRID   TYPE SPFLI-CARRID,
         CONNID   TYPE S_CONN_ID,
         CITYFROM TYPE S_FROM_CIT,
         CITYTO   TYPE S_TO_CITY,
       END OF SPFLITYPE.

DATA ITSCARR TYPE TABLE OF SCARRTYPE  INITIAL SIZE 0.
DATA ITSPFLI TYPE TABLE OF SPFLITYPE  INITIAL SIZE 0.

DATA WASCARR TYPE SCARRTYPE.
DATA WASPFLI TYPE SPFLITYPE.

START-OF-SELECTION.
  SELECT CARRNAME CARRID  CURRCODE
    FROM SCARR
    INTO TABLE ITSCARR.

  LOOP AT ITSCARR INTO WASCARR.
    WRITE: / WASCARR-CARRNAME,WASCARR-CARRID,WASCARR-CURRCODE.
  ENDLOOP.

AT LINE-SELECTION.
  WRITE: 'SY-LISEL:', SY-LISEL. "SY-LISEL contains all fields of the value selected from Basic List
  SKIP 2.
  PERFORM GETSPFLI.
  WRITE:/ 'SY-SUBRC After invoking GETSPFLI', SY-SUBRC.
  IF SY-SUBRC = 0.
    PERFORM DISPSPFLI.
  ELSE.
    WRITE / 'No Record found in SPFLI'.
  ENDIF.

FORM GETSPFLI.
  SELECT CARRID CONNID CITYFROM CITYTO
    INTO TABLE ITSPFLI FROM SPFLI
  WHERE CARRID = SY-LISEL. "This comparison will not work as SY-LISEL contains all fields
ENDFORM.

FORM DISPSPFLI.
  LOOP AT ITSPFLI INTO WASPFLI.
    WRITE:/ WASPFLI-CARRID , WASPFLI-CONNID ,WASPFLI-CITYFROM,
    WASPFLI-CITYTO.
  ENDLOOP.
ENDFORM.