REPORT Z NO STANDARD PAGE HEADING.
DATA ITSCARR TYPE TABLE OF SCARR-CARRID  INITIAL SIZE 0.
DATA WASCARRID TYPE SCARR-CARRID.

TYPES: BEGIN OF SPFLITYPE,
         CARRID   TYPE SPFLI-CARRID,
         CONNID   TYPE S_CONN_ID,
         CITYFROM TYPE S_FROM_CIT,
         CITYTO   TYPE S_TO_CITY,
       END OF SPFLITYPE.
DATA ITSPFLI TYPE TABLE OF SPFLITYPE  INITIAL SIZE 0.
DATA WASPFLI TYPE SPFLITYPE.

START-OF-SELECTION.
  SELECT CARRID
    FROM SCARR
    INTO TABLE ITSCARR.

  LOOP AT ITSCARR INTO WASCARRID.
    WRITE: / WASCARRID.
  ENDLOOP.

AT LINE-SELECTION.
  WRITE: 'SY-LISEL:', SY-LISEL.
  SKIP 2.

  SELECT CARRID CONNID CITYFROM CITYTO
  INTO TABLE ITSPFLI FROM SPFLI
  WHERE CARRID = SY-LISEL.
  IF SY-SUBRC = 0.
    LOOP AT ITSPFLI INTO WASPFLI.
      WRITE:/ WASPFLI-CARRID , WASPFLI-CONNID ,WASPFLI-CITYFROM,
      WASPFLI-CITYTO.
    ENDLOOP.
  ELSE.
    WRITE 'No Record found in SPFLI'.
  ENDIF.