REPORT  Z.

TABLES SCARR.

PARAMETERS CITY_FR TYPE SPFLI-CITYFROM.
PARAMETERS CITY_TO TYPE SPFLI-CITYTO.
PARAMETERS DATUM   TYPE SY-DATUM DEFAULT SY-DATUM.
SELECT-OPTIONS SCARRID FOR SCARR-CARRID.

INITIALIZATION.
    CITY_FR = 'NEW YORK'. 
    CITY_TO = 'FRANKFURT'. "Assigning values to parameters
    SCARRID-LOW = 'AA'. 
    SCARRID-HIGH = 'DL'.
    SCARRID-SIGN = 'I'. 
    SCARRID-OPTION = 'BT'.
    APPEND CARRID.

    DATUM+6(2) = '01'. "20200713 today's date

START-OF-SELECTION.
    WRITE:/ 'CITY_FR:', CITY_FR.
    WRITE:/ 'CITY_TO:', CITY_TO.
    WRITE:/ 'Carrid:',CARRID. 
    WRITE:/ 'Date:', DATUM.