REPORT  ZVKCLASSB1.
CLASS EMPLOYEE DEFINITION.
  PUBLIC SECTION.
    METHODS:
      SET_ATTRIBUTES
        IMPORTING IM_EMPLOYEE_NO   TYPE I
                  IM_EMPLOYEE_NAME TYPE STRING,
      DISPLAY_ATTRIBUTES.
  PRIVATE SECTION.
*--------------------------------------------------------------------
    DATA: NO   TYPE I,
          NAME TYPE STRING.
ENDCLASS.
*--- Employee - Implementation
CLASS EMPLOYEE IMPLEMENTATION.
  METHOD  SET_ATTRIBUTES.
    NO = IM_EMPLOYEE_NO.
    NAME = IM_EMPLOYEE_NAME.
  ENDMETHOD.

  METHOD DISPLAY_ATTRIBUTES.
    WRITE:/ 'Employee', NO, NAME.

  ENDMETHOD.
ENDCLASS.

*******************************************************
CLASS BLUECOLLAR_EMPLOYEE DEFINITION
           INHERITING FROM EMPLOYEE.
  PUBLIC SECTION.
    METHODS:
      SET_ATTRIBUTES REDEFINITION,
      DISPLAY_ATTRIBUTES REDEFINITION.
  PRIVATE SECTION.
    DATA HOURS TYPE I.
ENDCLASS.

*---- CLASS BlueCollar_Employee IMPLEMENTATION
CLASS BLUECOLLAR_EMPLOYEE IMPLEMENTATION.
  METHOD  SET_ATTRIBUTES.
    SUPER->SET_ATTRIBUTES( IM_EMPLOYEE_NO  = IM_EMPLOYEE_NO
                     IM_EMPLOYEE_NAME = IM_EMPLOYEE_NAME ).

    HOURS = 5.
  ENDMETHOD.

  METHOD DISPLAY_ATTRIBUTES.
    SUPER->DISPLAY_ATTRIBUTES( ).
    WRITE HOURS.
  ENDMETHOD.
ENDCLASS.

DATA:
* Object references
  O_BLUECOLLAR_EMPLOYEE1  TYPE REF TO BLUECOLLAR_EMPLOYEE.

START-OF-SELECTION.
* Create bluecollar employee obeject
  CREATE OBJECT O_BLUECOLLAR_EMPLOYEE1.
  CALL METHOD O_BLUECOLLAR_EMPLOYEE1->SET_ATTRIBUTES
    EXPORTING
      IM_EMPLOYEE_NO   = 1
      IM_EMPLOYEE_NAME = 'Gylle Karen'.
  CALL METHOD O_BLUECOLLAR_EMPLOYEE1->DISPLAY_ATTRIBUTES.