REPORT  Z.
CLASS EMPLOYEE DEFINITION.
  PUBLIC SECTION.
    METHODS:
      CONSTRUCTOR
        IMPORTING IM_EMPLOYEE_NO   TYPE I
                  IM_EMPLOYEE_NAME TYPE STRING,
      DISPLAY_ATTRIBUTES.
  PRIVATE SECTION.
    DATA: NO   TYPE I,
          NAME TYPE STRING.
ENDCLASS.
*--- Employee - Implementation
CLASS EMPLOYEE IMPLEMENTATION.
  METHOD  CONSTRUCTOR.
    NO = IM_EMPLOYEE_NO.
    NAME = IM_EMPLOYEE_NAME.
  ENDMETHOD.

  METHOD DISPLAY_ATTRIBUTES.
    WRITE:/ 'Employee', NO, NAME.
  ENDMETHOD.
ENDCLASS.

*******************************************************
CLASS BLUECOLLAR_EMPLOYEE DEFINITION
           INHERITING FROM EMPLOYEE.
  PUBLIC SECTION.
    METHODS:
      "CONSTRUCTOR REDEFINITION,
      " constructor cannot be over defined
      CONSTRUCTOR   IMPORTING
                      IM_EMPLOYEE_NO   TYPE I
                      IM_EMPLOYEE_NAME TYPE STRING,
      DISPLAY_ATTRIBUTES REDEFINITION.
  PRIVATE SECTION.
    DATA:NO   TYPE I,
         NAME TYPE STRING.
ENDCLASS.

*---- CLASS BlueCollar_Employee IMPLEMENTATION
CLASS BLUECOLLAR_EMPLOYEE IMPLEMENTATION.
  METHOD  CONSTRUCTOR.
    CALL METHOD SUPER->CONSTRUCTOR(
        IM_EMPLOYEE_NO   = IM_EMPLOYEE_NO
        IM_EMPLOYEE_NAME = IM_EMPLOYEE_NAME ).
  ENDMETHOD.

  METHOD DISPLAY_ATTRIBUTES.
    SUPER->DISPLAY_ATTRIBUTES( ).
  ENDMETHOD.
ENDCLASS.

DATA:
* Object references
  O_BLUECOLLAR_EMPLOYEE1  TYPE REF TO BLUECOLLAR_EMPLOYEE.

START-OF-SELECTION.
* Create bluecollar employee obeject
  CREATE OBJECT O_BLUECOLLAR_EMPLOYEE1
    EXPORTING
      IM_EMPLOYEE_NO   = 1
      IM_EMPLOYEE_NAME = 'Gylle Karen'.
  CALL METHOD O_BLUECOLLAR_EMPLOYEE1->DISPLAY_ATTRIBUTES.