REPORT Z.

TYPES: BEGIN OF TYEMPDEPT,
         MANDT       TYPE Z104329DBVIEW2-MANDT,
         DEPT_DEPTNO TYPE Z104329DBVIEW2-DEPT_DEPTNO,
         DNAME       TYPE Z104329DBVIEW2-DNAME,
         LOC         TYPE Z104329DBVIEW2-LOC,
         EMPNO       TYPE Z104329DBVIEW2-EMPNO,
         ENAME       TYPE Z104329DBVIEW2-ENAME,
         SAL         TYPE Z104329DBVIEW2-SAL,
         EMP_DEPTNO  TYPE Z104329DBVIEW2-EMP_DEPTNO,
       END OF TYEMPDEPT.
DATA ITEMPDEPT TYPE STANDARD TABLE OF TYEMPDEPT.
DATA WA TYPE TYEMPDEPT.

WA-MANDT = 100. WA-DEPT_DEPTNO = 99. WA-DNAME = 'zzz'. WA-LOC = 'zzz'.
WA-EMPNO = '8888'. WA-ENAME = 'Shyam'. WA-SAL = '6788'. WA-EMP_DEPTNO = 99.

INSERT  Z104329MAINVIEW2 FROM WA.

*Cannot Insert. Error. View is not defined in ABAP Dictionary as table, 
*projection view or database view.  