*CREATES A RANKING OF FIVE FLIGHTS OF A CONNECTION SHOWING THE MOST FREE SEATS.
REPORT Z104329PGM2 NO STANDARD PAGE HEADING.
PARAMETERS: P_CARRID TYPE SFLIGHT-CARRID,
            P_CONNID TYPE SFLIGHT-CONNID.

TYPES: BEGIN OF FLIGHTTYPE,
         FLDATE   TYPE SFLIGHT-FLDATE,
         SEATSMAX TYPE SFLIGHT-SEATSMAX,
         SEATSOCC TYPE SFLIGHT-SEATSOCC,
         SEATSFREE TYPE SFLIGHT-SEATSOCC,
       END OF FLIGHTTYPE.
DATA: FLIGHTDATA TYPE  FLIGHTTYPE.
DATA: ITSFLIGHT TYPE STANDARD TABLE OF FLIGHTTYPE INITIAL SIZE 5.

SELECT FLDATE SEATSMAX SEATSOCC
FROM SFLIGHT
INTO FLIGHTDATA
WHERE CARRID = P_CARRID AND
CONNID = P_CONNID.
  FLIGHTDATA-SEATSFREE = FLIGHTDATA-SEATSMAX - FLIGHTDATA-SEATSOCC.
  APPEND FLIGHTDATA TO ITSFLIGHT SORTED BY SEATSFREE.
ENDSELECT.

LOOP AT ITSFLIGHT INTO FLIGHTDATA .
  WRITE:/ FLIGHTDATA-FLDATE,
  FLIGHTDATA-SEATSMAX, FLIGHTDATA-SEATSOCC,
  FLIGHTDATA-SEATSFREE.
ENDLOOP.