REPORT Z.
TYPES: BEGIN OF FLIGHTTYPE,
        CARRID    TYPE SFLIGHT-CARRID,
        CONNID    TYPE SFLIGHT-CONNID ,
        FLDATE   TYPE SFLIGHT-FLDATE,
        SEATSMAX  TYPE SFLIGHT-SEATSMAX,
        SEATSOCC  TYPE SFLIGHT-SEATSOCC,
        PLANETYPE TYPE SFLIGHT-PLANETYPE,
         PRICE     TYPE SFLIGHT-PRICE,
       END OF   FLIGHTTYPE.
DATA: ITSFLIGHT1 TYPE STANDARD TABLE OF FLIGHTTYPE INITIAL SIZE 0,
      ITSFLIGHT2 TYPE STANDARD TABLE OF FLIGHTTYPE INITIAL SIZE 4,
      FLIGHTDATA TYPE  FLIGHTTYPE.

FLIGHTDATA-CARRID = 'AA'. FLIGHTDATA-CONNID = '17'. FLIGHTDATA-FLDATE = '20190731'.
FLIGHTDATA-PLANETYPE = '747-400'. FLIGHTDATA-SEATSMAX = 385. FLIGHTDATA-SEATSOCC = 375.
FLIGHTDATA-PRICE = 185.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '64'. FLIGHTDATA-FLDATE = '20190827'.
FLIGHTDATA-PLANETYPE = 'DC-10-10'. FLIGHTDATA-SEATSMAX = 380. FLIGHTDATA-SEATSOCC = 367.
FLIGHTDATA-PRICE = 230.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'DL'. FLIGHTDATA-CONNID = '17'. FLIGHTDATA-FLDATE = '20190923'.
FLIGHTDATA-PLANETYPE = 'A310-300'. FLIGHTDATA-SEATSMAX = 280. FLIGHTDATA-SEATSOCC = 271.
FLIGHTDATA-PRICE = 440.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '64'. FLIGHTDATA-FLDATE = '20190731'.
FLIGHTDATA-PLANETYPE = 'A319'. FLIGHTDATA-SEATSMAX = 220. FLIGHTDATA-SEATSOCC = 211.
FLIGHTDATA-PRICE = 145.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AA'. FLIGHTDATA-CONNID = '17'. FLIGHTDATA-FLDATE = '20190830'.
FLIGHTDATA-PLANETYPE = 'A310-300'. FLIGHTDATA-SEATSMAX = 280. FLIGHTDATA-SEATSOCC = 261.
FLIGHTDATA-PRICE = 200.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'DL'. FLIGHTDATA-CONNID = '64'. FLIGHTDATA-FLDATE = '20190923'.
FLIGHTDATA-PLANETYPE = 'A319'. FLIGHTDATA-SEATSMAX = 220. FLIGHTDATA-SEATSOCC = 213.
FLIGHTDATA-PRICE = 445.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AA'. FLIGHTDATA-CONNID = '64'. FLIGHTDATA-FLDATE = '20190828'.
FLIGHTDATA-PLANETYPE = '747-400'.  FLIGHTDATA-SEATSMAX = 385. FLIGHTDATA-SEATSOCC = 371.
FLIGHTDATA-PRICE = 430.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '17'. FLIGHTDATA-FLDATE = '20190828'.
FLIGHTDATA-PLANETYPE = 'A319'. FLIGHTDATA-SEATSMAX = 220. FLIGHTDATA-SEATSOCC = 205.
FLIGHTDATA-PRICE = 415.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AA'. FLIGHTDATA-CONNID = '64'. FLIGHTDATA-FLDATE = '20190802'.
FLIGHTDATA-PLANETYPE = 'A310-300'. FLIGHTDATA-SEATSMAX = 280. FLIGHTDATA-SEATSOCC = 271.
FLIGHTDATA-PRICE = 400.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '17'. FLIGHTDATA-FLDATE = '20190924'.
FLIGHTDATA-PLANETYPE = 'DC-10-10'. FLIGHTDATA-SEATSMAX = 380. FLIGHTDATA-SEATSOCC = 370.
FLIGHTDATA-PRICE = 345.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'DL'. FLIGHTDATA-CONNID = '17'. FLIGHTDATA-FLDATE = '20190826'.
FLIGHTDATA-PLANETYPE = 'A310-300'. FLIGHTDATA-SEATSMAX = 280. FLIGHTDATA-SEATSOCC = 270.
FLIGHTDATA-PRICE = 300.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '64'. FLIGHTDATA-FLDATE = '20190802'.
FLIGHTDATA-PLANETYPE = 'DC-10-10'. FLIGHTDATA-SEATSMAX = 380. FLIGHTDATA-SEATSOCC = 361.
FLIGHTDATA-PRICE = 315.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'DL'. FLIGHTDATA-CONNID = '64'. FLIGHTDATA-FLDATE = '20190826'.
FLIGHTDATA-PLANETYPE = 'A319'. FLIGHTDATA-SEATSMAX = 220. FLIGHTDATA-SEATSOCC = 213.
FLIGHTDATA-PRICE = 200.
APPEND FLIGHTDATA TO ITSFLIGHT1.

FLIGHTDATA-CARRID = 'AZ'. FLIGHTDATA-CONNID = '64'. FLIGHTDATA-FLDATE = '20190828'.
FLIGHTDATA-PLANETYPE = 'A310-300'. FLIGHTDATA-SEATSMAX = 380. FLIGHTDATA-SEATSOCC = 361.
FLIGHTDATA-PRICE = 185.
APPEND FLIGHTDATA TO ITSFLIGHT1.

LOOP AT ITSFLIGHT1 INTO FLIGHTDATA.
    APPEND  FLIGHTDATA TO ITSFLIGHT2 SORTED BY PRICE.
ENDLOOP.

LOOP AT ITSFLIGHT2 INTO FLIGHTDATA.
    WRITE:/ FLIGHTDATA-CARRID , FLIGHTDATA-CONNID,
    FLIGHTDATA-SEATSMAX , FLIGHTDATA-SEATSOCC , FLIGHTDATA-PRICE.
ENDLOOP.