REPORT  Z.
CLASS NUMBERS DEFINITION.
  PUBLIC SECTION.
    METHODS SETNUMBERS.
    METHODS CALC RAISING CX_SY_ZERODIVIDE.
    METHODS DISPLAYNUMBERS.
  PRIVATE SECTION.
    DATA: NUM1 TYPE I,
          NUM2 TYPE I,
          RES  TYPE I.
ENDCLASS.

CLASS NUMBERS IMPLEMENTATION.
  METHOD SETNUMBERS.
    NUM1 = 10.
    NUM2 = 0.
  ENDMETHOD.
  METHOD CALC.
    RES = NUM1 / NUM2.
  ENDMETHOD.

  METHOD DISPLAYNUMBERS.
    WRITE:/ 'Res is:' , RES.
  ENDMETHOD.
ENDCLASS.

START-OF-SELECTION.
  DATA ORF_1 TYPE REF TO CX_ROOT.
  DATA POSITION TYPE I.
  DATA PGMNAME TYPE SY-REPID.
  DATA NUM TYPE REF TO NUMBERS.
  CREATE OBJECT NUM.
  NUM->SETNUMBERS( ).
  TRY.
      NUM->CALC( ).
    CATCH CX_SY_ZERODIVIDE INTO ORF_1.
      WRITE / ORF_1->KERNEL_ERRID.
      WRITE / ORF_1->GET_TEXT( ).
      WRITE / ORF_1->GET_LONGTEXT( ).

      ORF_1->GET_SOURCE_POSITION(
                  IMPORTING  SOURCE_LINE  = POSITION
                             PROGRAM_NAME = PGMNAME ).
      WRITE: / 'Position:', POSITION.
      WRITE: / 'Program Name:', PGMNAME.
  ENDTRY.
  NUM->DISPLAYNUMBERS( ).