 # 3.
*MORE THAN ONE EVENT HANDLER METHOD CAN EXIST FOR SAME EVENT.


CLASS C1 DEFINITION.
  PUBLIC SECTION.
  "CREATING EVENT : E1
  EVENTS : E1.
  "CREATING AN EVENT HANDLING METHOD.
  METHODS : M1 FOR EVENT E1 OF C1.
  "METHOD TO RAISE THE EVENT
  METHODS : T1.
  ENDCLASS.

CLASS C2 DEFINITION.
  PUBLIC SECTION.
  "CREATING AN EVENT HANDLING METHOD.
  METHODS : M2 FOR EVENT E1 OF C1.
  ENDCLASS.

  CLASS C1 IMPLEMENTATION.
    "METHOD : T1 WILL RAISE THE EVENT
    METHOD : T1.
      WRITE:/5 'I AM T1, GOING TO RAISE EVENT E1'.
      RAISE EVENT E1.
    ENDMETHOD.
    "METHOD : M1 WILL BE CALLED WHEN THE VENT IS RAISE
    METHOD : M1.
      WRITE:/5 ' I AM THE EVENT HANDLER METHOD M1 IN C1'.
      ENDMETHOD.
      ENDCLASS.

  CLASS C2 IMPLEMENTATION.
   "METHOD : M2 WILL BE CALLED WHEN THE EVENT IS RAISED
    METHOD : M2.
      WRITE:/5 'I AM THE EVENT HANDLER METHOD M2 IN C2'.
      ENDMETHOD.
      ENDCLASS.

 START-OF-SELECTION.
      DATA : OREF1 TYPE REF TO C1,
            OREF2 TYPE REF TO C2.
      CREATE OBJECT : OREF1, OREF2.
      "REGISTERING THE EVENT HANDLER METHOD
      SET HANDLER OREF1->M1 FOR OREF1.
      "CALLING THE VENT WHICH WILL RAISE THE EVENT.
      CALL METHOD OREF1->T1.
      "DE-REGISTERING THE EARLIER EVENT HANDLER METHOD
      SET HANDLER OREF1->M1 FOR OREF1 ACTIVATION SPACE.
      "REGISTERING THE NEW EVENT HANDLER METHOD
      SET HANDLER OREF2->M2 FOR OREF1.
      "CALLING THE VENT WHICH WILL RAISE THE VENT.
      CALL METHOD OREF1->T1.