*&---------------------------------------------------------------------*
*& Report ZTRCAP_EVENTS
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*

*EVENT IS A MECHANISM BY WHICH METHOD OF ONE CLASS CAN RAISE METHOD
*OF ANOTHER CLASS, WITHOUT THE HAZARD OF INSTANTIATING THAT CLASS.
*STEPS ARE : 1) CREATE AN EVENT IN A CLASS. 2)CREATE A TRIGGERING METHOD
*              IN THE SAME CLASS WHICH WILL RAISE THE EVENT.
*            2) CREATE AN EVENT HANDLER METHOD FOR THE EVENT IN SAME/OTHER CLASS.
*            3) REGISTER THE EVENT HANDLER METHOD IN THE PROGRAM.

REPORT ZTRCAP_EVENTS.

* # 1.

*CLASS C1 DEFINITION.
*  PUBLIC SECTION.
** (1) CREATING EVENT : E1
*  EVENTS : E1.
** (2)  CREATING AN EVENT HANDLING METHOD. THIS METHOD CAN BELONG TO SAME OR DIFFEENT CLASS.
*  METHODS : M1 FOR EVENT E1 OF C1.
**METHODS TO RAISE THE EVENT
*  METHODS : T1.
*ENDCLASS.
*
*CLASS C1 IMPLEMENTATION.
**METHOD : M1 WILL BE CALLED WHEN THE EVENT IS RAISED
*METHOD : M1.
*  WRITE:/5 ' I AM THE EVENT HANDLER METHOD'.
*ENDMETHOD.
**METHOD : T1 WILL RAISE THE EVENT
*METHOD : T1.
*  WRITE:/5 'I AM T1, GOING TO RAISE EVENT E1'.
*  RAISE EVENT E1.
*ENDMETHOD.
*ENDCLASS.
*
*START-OF-SELECTION.
*DATA : OREF TYPE REF TO C1.
*CREATE OBJECT : OREF.
**REGISTERING THE EVENT HANDLER METHOD
*SET HANDLER OREF->M1 FOR OREF.
**CALLING THE EVENT WHICH WILL RAISE THE EVENT.
*CALL METHOD OREF->T1.

* # 2.
**EVENT WITH EVENT HANDLER METHOD IN DIFFERENT CLASS.
*

*CLASS C1 DEFINITION.
*  PUBLIC SECTION.
*  "CREATING EVENT : E1
*EVENTS : E1.
*  "TRIGGERING METHOD : T1
*  METHODS : T1.
*ENDCLASS.
*
*CLASS C2 DEFINITION.
*  PUBLIC SECTION.
*  "CREATING AN EVENT HANDLING METHOD.
*  METHODS : M2 FOR EVENT E1 OF C1.
*  ENDCLASS.
*
*  CLASS C1 IMPLEMENTATION.
*    "METHOD : T1 WILL RAISE THE EVENT.
*    METHOD : T1.
*    WRITE:/5 'I AM T1, GOING TO RAISE EVENT E1'.
*    RAISE EVENT E1.
*    ENDMETHOD.
*    ENDCLASS.
*
*  CLASS C2 IMPLEMENTATION.
*    "METHOD : M1 WILL BE CALLED WHEN THE EVENT IS RAISED
*    METHOD : M2.
*      WRITE:/5 ' I AM THE VENT HANDLER METHOD IN C2'.
*      ENDMETHOD.
*      ENDCLASS.
*
*      START-OF-SELECTION.
*      DATA : OREF1 TYPE REF TO C1,
*             OREF2 TYPE REF TO C2.
*      CREATE OBJECT : OREF1, OREF2.
*      "REGISTERING THE EVENT HANDLER METHOD.
*     SET HANDLER OREF2->M2 FOR OREF1.
*      "CALLING THE EVENT WHICH WILL RAISE THE EVENT.
*      CALL METHOD OREF1->T1.

* # 3.
**MORE THAN ONE VENT HANDLER METHOD CAN EXIST FOR SAME EVENT.
*

*CLASS C1 DEFINITION.
*  PUBLIC SECTION.
*  "CREATING EVENT : E1
*  EVENTS : E1.
*  "CREATING AN EVENT HANDLING METHOD.
*  METHODS : M1 FOR EVENT E1 OF C1.
*  "METHOD TO RAISE THE EVENT
*  METHODS : T1.
*  ENDCLASS.
*
*CLASS C2 DEFINITION.
*  PUBLIC SECTION.
*  "CREATING AN EVENT HANDLING METHOD.
*  METHODS : M2 FOR EVENT E1 OF C1.
*  ENDCLASS.
*
*  CLASS C1 IMPLEMENTATION.
*    "METHOD : T1 WILL RAISE THE EVENT
*    METHOD : T1.
*      WRITE:/5 'I AM T1, GOING TO RAISE EVENT E1'.
*      RAISE EVENT E1.
*    ENDMETHOD.
*    "METHOD : M1 WILL BE CALLED WHEN THE VENT IS RAISE
*    METHOD : M1.
*      WRITE:/5 ' I AM THE VENT HANDLER METHOD M1 IN C1'.
*      ENDMETHOD.
*      ENDCLASS.
*
*  CLASS C2 IMPLEMENTATION.
*   "METHOD : M2 WILL BE CALLED WHEN THE EVENT IS RAISED
*    METHOD : M2.
*      WRITE:/5 'I AM THE EVENT HANDLER METHOD M2 IN C2'.
*      ENDMETHOD.
*      ENDCLASS.
*
* START-OF-SELECTION.
*      DATA : OREF1 TYPE REF TO C1,
*            OREF2 TYPE REF TO C2.
*      CREATE OBJECT : OREF1, OREF2.
*      "REGISTERING THE EVENT HANDLER METHOD
*      SET HANDLER OREF1->M1 FOR OREF1.
*      "CALLING THE VENT WHICH WILL RAISE THE EVENT.
*      CALL METHOD OREF1->T1.
*      "DE-REGISTERING THE EARLIER EVENT HANDLER METHOD
*      SET HANDLER OREF1->M1 FOR OREF1 ACTIVATION SPACE.
*      "REGISTERING THE NEW EVENT HANDLER METHOD
*      SET HANDLER OREF2->M2 FOR OREF1.
*      "CALLING THE VENT WHICH WILL RAISE THE VENT.
*      CALL METHOD OREF1->T1.

* # 4.
**USING CLASS EVENTS IE USE OF STATIC EVENTS.
*

*CLASS C1 DEFINITION.
*  PUBLIC SECTION.
*  "CREATING EVENT : E1
*  CLASS-EVENTS : E1.
*  "CREATING AN EVENT HANDLING METHOD.
*  METHODS : M1 FOR EVENT E1 OF C1.
*  "METHOD TO RAISE THE EVENT
*  CLASS-METHODS : T1.
*  ENDCLASS.
*
*  CLASS C1 IMPLEMENTATION.
*    "METHOD : T1 WILL RAISE THE EVENT
*    METHOD : T1.
*      WRITE:/5 'I AM T1, GOING TO RAISE EVENT E1'.
*      RAISE EVENT E1.
*    ENDMETHOD.
*    "METHOD : M1 WILL BE CALLED WHEN THE VENT IS RAISE
*    METHOD : M1.
*      WRITE:/5 ' I AM THE EVENT HANDLER METHOD M1 IN C1'.
*      ENDMETHOD.
*  ENDCLASS.
*
*
*START-OF-SELECTION.
*DATA : OREF1 TYPE REF TO C1.
*CREATE OBJECT : OREF1.
*"REGISTERING THE VENT HANDLER METHOD
*SET HANDLER OREF1->M1.
*"CALLING THE VENT WHICH WILL RAISE THE VENT.
*CALL METHOD OREF1->T1.


* # 5.
*EVENTS WITH EXPORT PARAMETERS

CLASS C1 DEFINITION.
  PUBLIC SECTION.
  EVENTS : E1 EXPORTING VALUE(NUM1) TYPE I
                        VALUE(NUM2) TYPE I.
  METHODS : M1 FOR EVENT E1 OF C1
               IMPORTING NUM1
                         NUM2.
  METHODS : T1.
  ENDCLASS.

CLASS C1 IMPLEMENTATION.
  METHOD : M1.
    WRITE:/5 'FIRST INPUT' , NUM1.
    WRITE:/5 'SECOND INPUT', NUM2.
  ENDMETHOD.

  METHOD T1.
    RAISE EVENT E1 EXPORTING NUM1 = 420
                             NUM2 = 9211.
  ENDMETHOD.
  ENDCLASS.

  START-OF-SELECTION.
  DATA : OREF TYPE REF TO C1.
  CREATE OBJECT OREF.
  SET HANDLER OREF->M1 FOR OREF.
  CALL METHOD OREF->T1.