*# 5.
*EVENTS WITH EXPORT PARAMETERS

CLASS C1 DEFINITION.
  PUBLIC SECTION.
  EVENTS : E1 EXPORTING VALUE(NUM1) TYPE I
                        VALUE(NUM2) TYPE I.
  METHODS : M1 FOR EVENT E1 OF C1
               IMPORTING NUM1
                         NUM2.
  METHODS : T1.
  ENDCLASS.

CLASS C1 IMPLEMENTATION.
  METHOD : M1.
    WRITE:/5 'FIRST INPUT' , NUM1.
    WRITE:/5 'SECOND INPUT', NUM2.
  ENDMETHOD.

  METHOD T1.
    RAISE EVENT E1 EXPORTING NUM1 = 420
                             NUM2 = 9211.
  ENDMETHOD.
  ENDCLASS.

  START-OF-SELECTION.
  DATA : OREF TYPE REF TO C1.
  CREATE OBJECT OREF.
  SET HANDLER OREF->M1 FOR OREF.
  CALL METHOD OREF->T1.