REPORT Z.
"OLD METHOD
DATA PCARRID TYPE SPFLI-CARRID VALUE 'AA'.
TYPES: BEGIN OF STR,
  CARRID TYPE SPFLI-CARRID,
  CONNID TYPE SPFLI-CONNID,
  CITYFROM TYPE SPFLI-CITYFROM,
  CITYTO TYPE SPFLI-CITYTO,
  END OF STR.

DATA: ITAB TYPE TABLE OF STR,
      WA TYPE STR.

 SELECT
   CARRID
   CONNID
   CITYFROM
   CITYTO
   FROM SPFLI
   INTO TABLE ITAB WHERE CARRID = PCARRID.

LOOP AT ITAB INTO WA.
  WRITE:/ WA-CARRID, WA-CONNID, WA-CITYFROM, WA-CITYTO.
  ENDLOOP.

__________________________________________________________

"NEW METHOD

REPORT Z.

DATA(PCARRID) =  'AA'.

SELECT
   CARRID,
   CONNID,
   CITYFROM,
   CITYTO
   FROM SPFLI
   INTO TABLE @DATA(ITAB)
  WHERE CARRID = @PCARRID.

*LOOP AT ITAB INTO DATA(WA).
*  WRITE:/ WA-CARRID, WA-CONNID, WA-CITYFROM, WA-CITYTO.
*ENDLOOP.

CL_DEMO_OUTPUT=>DISPLAY( ITAB ).

