REPORT Z.
TYPES: BEGIN OF FLIGHTTYPE,
         MANDT TYPE  SFLIGHT-MANDT,
         CARRID TYPE SFLIGHT-CARRID,
         CONNID TYPE SFLIGHT-CONNID,
         SEATSMAX  TYPE SFLIGHT-SEATSMAX,
         SEATSOCC  TYPE SFLIGHT-SEATSOCC,
       END OF   FLIGHTTYPE.
DATA: ITSFLIGHT TYPE STANDARD TABLE OF FLIGHTTYPE
      WITH NON-UNIQUE KEY CARRID CONNID INITIAL SIZE 0,
      WA TYPE  FLIGHTTYPE.

PERFORM SELECTFROMDB.
PERFORM READWITHTABLEKEY.


FORM SELECTFROMDB.
  SELECT MANDT CARRID CONNID SEATSMAX SEATSOCC
      FROM SFLIGHT
    INTO TABLE ITSFLIGHT.
ENDFORM.


FORM READWITHTABLEKEY.
CLEAR WA.
  READ TABLE ITSFLIGHT INTO WA
  WITH TABLE KEY
  CARRID = 'AA'
  CONNID = '0017'.
  WRITE: 'SY-SUBRC IS :' , SY-SUBRC.
  IF SY-SUBRC = 0.
    PERFORM DISP.
  ENDIF.

ENDFORM.

FORM DISP.
      WRITE:/ WA-CARRID , WA-CONNID,
    WA-SEATSMAX , WA-SEATSOCC.
  
ENDFORM.
