REPORT Z.
"DEFAULT IS STANDARD TABLE
"IF NO TYPE IS SPECFIED IT IS A STANDARD TABLE
"In a standard table, key may be given
"Standard table cannot have a unique key
TYPES : BEGIN OF TY_SCARR,
          MANDT    TYPE SCARR-MANDT,
          CARRID   TYPE SCARR-CARRID,
          CARRNAME TYPE SCARR-CARRNAME,
          CURRCODE TYPE SCARR-CURRCODE,
          URL      TYPE SCARR-URL,
        END OF TY_SCARR.

DATA ITSCARR TYPE TABLE OF TY_SCARR INITIAL SIZE 0.
*DATA WA TYPE TY_SCARR
*OR
DATA WA LIKE LINE OF ITSCARR.
PERFORM SELECTFROMDB.
PERFORM READCOMPARING.

FORM SELECTFROMDB.
  SELECT MANDT CARRID CARRNAME CURRCODE URL  UP TO 10 ROWS
      FROM SCARR
      INTO TABLE ITSCARR.
ENDFORM.

FORM READCOMPARING.
  CLEAR WA.
  WA-MANDT = 100.
  WA-CARRID = 'AA'.
 " WA-CARRNAME = 'American Airlines'.
  WA-CURRCODE = 'USD'.
  WA-URL  = 'http://www.aa.com'.
  WA-CARRNAME = 'GGGG'.
 " READ TABLE ITSCARR INTO WA INDEX 4.
 "  READ TABLE ITSCARR INTO WA INDEX 4 COMPARING ALL FIELDS. "all fields is default
 "   READ TABLE ITSCARR INTO WA INDEX 4 COMPARING CARRID CARRNAME.
    READ TABLE ITSCARR INTO WA INDEX 1 COMPARING CARRID CARRNAME.
  "  READ TABLE ITSCARR INTO WA COMPARING CARRID CARRNAME."NOT ALLOWED
  WRITE: 'SY-SUBRC IS :' , SY-SUBRC.
  IF SY-SUBRC = 0.
    PERFORM DISP.
  ENDIF.
ENDFORM.

FORM DISP.
  WRITE:/ WA-MANDT,WA-CARRID,WA-CARRNAME,WA-CURRCODE,
  WA-URL.
ENDFORM.