REPORT  Z.
*Example of standard table
*INSERT IN STANDARD TABLE
TYPES : BEGIN OF TY_SCARR,
          MANDT    TYPE SCARR-MANDT,
          CARRID   TYPE SCARR-CARRID,
          CARRNAME TYPE SCARR-CARRNAME,
          CURRCODE TYPE SCARR-CURRCODE,
          URL      TYPE SCARR-URL,
        END OF TY_SCARR.

DATA ITSCARR1 TYPE TABLE OF TY_SCARR INITIAL SIZE 0.
DATA WA1 TYPE TY_SCARR.

DATA ITSCARR2 TYPE TABLE OF TY_SCARR INITIAL SIZE 0.
DATA WA2 TYPE TY_SCARR.

PERFORM SELECTFROMDB.
PERFORM ADDTOITSCARR2.
PERFORM INSERT_INTO_INTTABLE.
PERFORM DISP.

FORM SELECTFROMDB.
 SELECT MANDT CARRID CARRNAME CURRCODE URL  UP TO 5 ROWS
       FROM SCARR
       INTO TABLE ITSCARR1.
ENDFORM.

FORM INSERT_INTO_INTTABLE.

*1
INSERT LINES OF ITSCARR2 INTO TABLE ITSCARR1.
*Records are appended AT LAST
*NO INDEX CAN BE SPECIFIED HERE

*2
INSERT LINES OF ITSCARR2 FROM 2 TO 4 INTO TABLE ITSCARR1.
*Specified Records are appended AT LAST
*NO INDEX CAN BE SPECIFIED HERE

*3
  INSERT LINES OF ITSCARR2 FROM 2 TO 4 INTO ITSCARR1 INDEX 2.
*Records are inserted from index 2 in itscarr1

ENDFORM.

FORM DISP.
 LOOP AT ITSCARR1 INTO WA1.
    WRITE:/ 'CARRID IS :', WA1-CARRID.
    WRITE: 'CARRNAME IS :', WA1-CARRNAME.
    WRITE: 'CURRCODE IS :', WA1-CURRCODE.
  ENDLOOP.
ENDFORM.

FORM ADDTOITSCARR2.
  WA2-MANDT = 100.
  WA2-CARRID = 'AI'. WA2-CARRNAME  = 'Air India'.
  WA2-CURRCODE = 'INR'. WA2-URL = 'www.airindia.com'.
  APPEND WA2 TO ITSCARR2.

  WA2-CARRID = 'QA'. WA2-CARRNAME  = 'Qatar Airways'.
  WA2-CURRCODE = 'AED'. WA2-URL = 'www.qatarairways.com'.
  APPEND WA2 TO ITSCARR2.

  WA2-CARRID = 'EM'. WA2-CARRNAME  = 'Emirates'.
  WA2-CURRCODE = 'AED'. WA2-URL = 'www.emirates.com'.
  APPEND WA2 TO ITSCARR2.
ENDFORM.