REPORT Z.
DATA LT_FLIGHTS_ALL TYPE STANDARD TABLE OF SPFLI
                     WITH NON-UNIQUE SORTED KEY CARRID
          COMPONENTS CARRID.

DATA LT_FLIGHT_LH   TYPE STANDARD TABLE OF SPFLI.
SELECT *  FROM SPFLI
          INTO TABLE @LT_FLIGHTS_ALL.
IF SY-SUBRC = 0.
  LT_FLIGHT_LH = FILTER #( LT_FLIGHTS_ALL USING KEY CARRID
                                        WHERE CARRID = 'LH ' ).
ENDIF.
CL_DEMO_OUTPUT=>DISPLAY( LT_FLIGHT_LH ).