REPORT Z.
DATA LT_FLIGHTS_ALL  TYPE STANDARD TABLE OF SPFLI
                     WITH NON-UNIQUE SORTED KEY CARRID
                     COMPONENTS CARRID.
DATA LT_FLIGHT_LH TYPE STANDARD TABLE OF SPFLI.

SELECT *  FROM SPFLI
          INTO TABLE @LT_FLIGHTS_ALL.

* Create a filter internal table with multiple values
DATA FILTER_TAB  TYPE SORTED TABLE OF SCARR-CARRID
                 WITH UNIQUE KEY TABLE_LINE.
FILTER_TAB = VALUE #( ( 'AA ' ) ( 'LH ' ) ).

* Apply filters
LT_FLIGHT_LH = FILTER #( LT_FLIGHTS_ALL IN FILTER_TAB
                                           WHERE CARRID = TABLE_LINE ).
CL_DEMO_OUTPUT=>DISPLAY( LT_FLIGHT_LH ).