REPORT Z.
DATA: LT_FLIGHTS_ALL TYPE STANDARD TABLE OF SPFLI,
      LT_FLIGHT_LH   TYPE STANDARD TABLE OF SPFLI.

SELECT *  FROM SPFLI
          INTO TABLE @LT_FLIGHTS_ALL.
IF SY-SUBRC = 0.
  LOOP AT LT_FLIGHTS_ALL INTO DATA(LS_FLIGHT) WHERE CARRID = 'LH'.
    APPEND LS_FLIGHT TO LT_FLIGHT_LH.
    CLEAR LS_FLIGHT.
  ENDLOOP.
ENDIF.

CL_DEMO_OUTPUT=>DISPLAY( LT_FLIGHT_LH ).