REPORT Z.
SELECT
  SF~*,
  SP~CITYFROM,
  SP~CITYTO
  FROM SPFLI AS SP
  INNER JOIN SFLIGHT AS SF
  ON SF~CARRID = SP~CARRID
  AND SF~CONNID = SP~CONNID
  WHERE SF~CARRID = 'AA'
  INTO TABLE @DATA(ITAB).


LOOP AT ITAB INTO DATA(WA).
  WRITE: / WA-SF-CARRID , WA-SF-CONNID , WA-SF-FLDATE ,WA-CITYFROM , WA-CITYTO.
ENDLOOP.

*We retrive all the fields of the DB table SFLIGHT. This goes in a structure SF.
*Hence   WA-SF-CARRID , WA-SF-CONNID,  WA-SF-FLDATE
*The above 3 are fields of Sflight table