REPORT Z.
"OLD METHOD
DATA: A TYPE I VALUE 4,
      B TYPE I VALUE 7.
DATA RESULT TYPE I.

CLASS ABC DEFINITION.
  PUBLIC SECTION.
    METHODS ADD EXPORTING R TYPE I.
ENDCLASS.

CLASS ABC IMPLEMENTATION.
  METHOD ADD.
    R = A + B.
    WRITE: R.
  ENDMETHOD.
ENDCLASS.

START-OF-SELECTION.
  DATA: OBJ1 TYPE REF TO ABC.
  CREATE OBJECT: OBJ1.
  OBJ1->ADD( IMPORTING R = RESULT ) .
  WRITE RESULT.

"NEW METHOD
DATA: A TYPE I VALUE 4,
      B TYPE I VALUE 7.
CLASS ABC DEFINITION.
  PUBLIC SECTION.
    METHODS ADD EXPORTING R TYPE I.
ENDCLASS.

CLASS ABC IMPLEMENTATION.
  METHOD ADD.
    R = A + B.
    WRITE: R.
  ENDMETHOD.
ENDCLASS.

START-OF-SELECTION.
  DATA(OBJ1)  = NEW ABC( ).
  OBJ1->ADD( IMPORTING R = DATA(RESULT) ).
  WRITE RESULT.