REPORT Z NO STANDARD PAGE HEADING.

TYPES: BEGIN OF SCARRTYPE,
         CARRID   TYPE SCARR-CARRID,
         CARRNAME TYPE S_CARRNAME,
         CURRCODE TYPE S_CURRCODE,
       END OF SCARRTYPE.

TYPES: BEGIN OF SPFLITYPE,
         CARRID   TYPE SPFLI-CARRID,
         CONNID   TYPE S_CONN_ID,
         CITYFROM TYPE S_FROM_CIT,
         CITYTO   TYPE S_TO_CITY,
       END OF SPFLITYPE.

TYPES: BEGIN OF SFLIGHTTYPE,
          CARRID TYPE SFLIGHT-CARRID,
          CONNID TYPE S_CONN_ID,
          FLDATE TYPE S_DATE,
          PRICE TYPE S_PRICE,
          PLANETYPE TYPE S_PLANETYE,
        END OF SFLIGHTTYPE.

DATA ITSCARR TYPE TABLE OF SCARRTYPE INITIAL SIZE 0.
DATA ITSPFLI TYPE TABLE OF SPFLITYPE INITIAL SIZE 0.
DATA ITSFLIGHT  TYPE TABLE OF SFLIGHTTYPE   INITIAL SIZE 0.

DATA WASCARR   TYPE SCARRTYPE.
DATA WASPFLI   TYPE SPFLITYPE.
DATA WASFLIGHT TYPE SFLIGHTTYPE.

START-OF-SELECTION.
SELECT CARRID CARRNAME CURRCODE
  FROM SCARR
  INTO TABLE ITSCARR.

LOOP AT ITSCARR INTO WASCARR.
   WRITE: / WASCARR-CARRID,WASCARR-CARRNAME,WASCARR-CURRCODE.
   HIDE WASCARR-CARRID.
ENDLOOP.

AT LINE-SELECTION.
WRITE: 'SY-LISEL:', SY-LISEL.
SKIP 2.
IF SY-LSIND = 1.
  PERFORM DISPSPFLI.
ELSEIF SY-LSIND = 2.
  PERFORM DISPSFLIGHT.
ELSE.
  MESSAGE E001(Z204329MSGCLASS) WITH 'Maximum list navigation is 2'.  
ENDIF.

FORM DISPSPFLI.
  PERFORM GETSPFLI.
  IF SY-SUBRC = 0.
    PERFORM DISPLAYSPFLI.
  ELSE.
    WRITE 'No Record IN SPFLI'.
  ENDIF.
ENDFORM.

FORM GETSPFLI.
  SELECT CARRID CONNID CITYFROM CITYTO
    INTO TABLE ITSPFLI FROM SPFLI
  WHERE CARRID = WASCARR-CARRID.
ENDFORM.

FORM DISPLAYSPFLI.
  LOOP AT ITSPFLI INTO WASPFLI.
    WRITE:/ WASPFLI-CARRID , WASPFLI-CONNID ,WASPFLI-CITYFROM,
    WASPFLI-CITYTO.
    HIDE WASPFLI-CONNID.
  ENDLOOP.
ENDFORM.

FORM DISPSFLIGHT.
  PERFORM GETSFLIGHT.
  IF SY-SUBRC = 0.
    PERFORM DISPLAYSFLIGHT.
  ELSE.
    WRITE 'No Record IN SFLIGHT'.
  ENDIF.
ENDFORM.

FORM GETSFLIGHT.
  SELECT CARRID CONNID FLDATE PRICE PLANETYPE
    INTO TABLE ITSFLIGHT FROM SFLIGHT
  WHERE CARRID = WASCARR-CARRID AND CONNID = WASPFLI-CONNID.
ENDFORM.

FORM DISPLAYSFLIGHT.
  LOOP AT ITSFLIGHT INTO WASFLIGHT.
    WRITE:/ WASFLIGHT-CARRID , WASFLIGHT-CONNID ,WASFLIGHT-FLDATE,
    WASFLIGHT-PRICE, WASFLIGHT-PLANETYPE.
  ENDLOOP.
ENDFORM.